# Compare all of Parameters:
* norm_random vs. norm_subjectindipendent
* learn-rate: 1e-3 vs. 1e-4 vs. 1e-5 vs. 1e-6
* batch-size: 64 vs. 32 vs. 128
* Dataset-size(train & test): (1000 & 200) vs. (10000 & 2000) 


In [1]:
# 1: Bib

import time

import os
import re
import json
import csv
from pathlib import Path
from scipy import stats
import pandas as pd
import numpy as np
from tqdm import tqdm
from PIL import Image
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

import torch
import torch.nn as nn
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torchvision import transforms
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)
from torchvision.models import (
    resnet18,
    ResNet18_Weights
)
from datetime import datetime

from torch.utils.tensorboard import SummaryWriter



I0000 00:00:1789571130.399258   14189 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1789571132.112652   14189 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


In [2]:

# 2: Dataset Class: transfer CSV in PyTorch.
class GazeDataset(Dataset):

    def __init__(self, csv_file, transform=None, dataset_size=None, read_all4once=True):

        self.df = pd.read_csv(csv_file)
        self.transform = transform
        self.dataset_size = dataset_size if dataset_size is not None else len(self.df)
        self.read_all4once = read_all4once

        if self.read_all4once:
            img = Image.new("RGB", (500, 300))  # any size
            out = transform(img)
            self.images = torch.zeros([self.dataset_size] + list(out.shape))
            self.targets = torch.zeros(self.dataset_size, 2)

        for idx in tqdm(range(self.dataset_size)):

            row = self.df.iloc[idx]

            image = Image.open(
                row["image_name"]
            ).convert("RGB")

            self.targets[idx] = torch.tensor(
                [row["x"], row["y"]],
                dtype=torch.float32
            )

            if self.transform:
                self.images[idx] = self.transform(image)
            else:
                self.images[idx] = image

    def __len__(self):

        return self.dataset_size

    def __getitem__(self, idx):

        return self.images[idx], self.targets[idx]

In [3]:

# 5: func-Diagonal-Error:
def diagonal_errors(model, loader, device):
    model.eval()

    targets_list = []
    preds_list = []

    with torch.no_grad():
        for images, targets in loader:
            images = images.to(device)
            preds = model(images)
            targets_list.append(targets.cpu().numpy())
            preds_list.append(preds.cpu().numpy())

    targets = np.concatenate(targets_list, axis=0)
    predictions = np.concatenate(preds_list, axis=0)
    
    mae = mean_absolute_error(targets, predictions)
    
    rmse = np.sqrt(mean_squared_error(targets, predictions))

    diagonal_error_pct = np.round(100 * (rmse / np.sqrt(2)), 5)

    errors = np.sqrt(
        np.sum(
            (predictions-targets)**2,
            axis=1
        )
    )

    print(f"MAE : {mae:.4f} \t RMSE: {rmse:.4f} ")
    # print(f"RMSE: {rmse:.4f}")
    print(f"Diagonal-Error %: {diagonal_error_pct:.4f} %")

    return mae, rmse, diagonal_error_pct

In [4]:
def evaluate_model(model, loader, device):

    model.eval()

    targets_list = []
    preds_list = []

    with torch.no_grad():
        for images, targets in loader:
            images = images.to(device)
            preds = model(images)
            targets_list.append(targets.cpu().numpy())
            preds_list.append(preds.cpu().numpy())

    targets = np.concatenate(targets_list, axis=0)
    predictions = np.concatenate(preds_list, axis=0)
    
    # mae = mean_absolute_error(targets, predictions)
    
    # rmse = np.sqrt(mean_squared_error(targets, predictions))

    # diagonal_error_pct = np.round(100 * (rmse / np.sqrt(2)), 5)

    errors = np.sqrt(
        np.sum(
            (predictions-targets)**2,
            axis=1
        )
    )

    # print(f"MAE : {mae:.4f} \t RMSE: {rmse:.4f} ")
    # print(f"RMSE: {rmse:.4f}")
    # print(f"Diagonal-Error %: {diagonal_error_pct:.4f} %")

    # return mae, rmse, diagonal_error_pct, targets, predictions, errors
    return targets, predictions, errors

In [5]:
class GaussianActivation(nn.Module):

    def __init__(self, sigma=1.0):
        super().__init__()
        self.sigma = sigma

    def forward(self, x):
        return torch.exp(
            -(x ** 2) / (2 * self.sigma ** 2)
        )

In [6]:
def sensitive_loss(preds, targets):

    x_total = 0.0

    for i in range(len(targets)):

        x = criterion_base(preds[i], targets[i])

        distance_from_center = (
            torch.abs(targets[i][0] - 0.5) +
            torch.abs(targets[i][1] - 0.5)
        )

        weight = 1.0 + distance_from_center

        x_total += x * weight

    return x_total / len(targets)

In [7]:
def confidence_interval(data, confidence=0.95):

    data = np.asarray(data)

    n = len(data)

    mean = np.mean(data)
    std = np.std(data, ddof=1)

    standard_error = std / np.sqrt(n)

    t_value = stats.t.ppf(
        (1 + confidence) / 2,
        df=n - 1
    )

    margin = t_value * standard_error

    lower = mean - margin
    upper = mean + margin

    return mean, lower, upper

# Hypoparameter:

* dataset_size (train-size & test-size)
* batch_size 
* learn-rate
* norm_random vs. norm_subject


In [36]:
# Hypoparameter:

name_dataset_type = ['norm_labels.csv', 'labels.csv']
dataset_size_type = [[10000, 2000], [1000, 200]]
dataset_type = ["norm_subject", "norm_random"]
batch_size_type = [32, 64, 128]
lr_type = [1e-3, 1e-4, 1e-5, 1e-6] 
epochs_num = [1, 2, 10, 25, 500]



optimizer_name = "AdamW"

# ##########################################################################
# 1.type Dataset: 'norm_labels.csv' or 'labels.csv'
dataset_name = name_dataset_type[0]                       # norm_labels.csv
# dataset_name = name_dataset_type[1]                       # labels.csv
print(f"\n dataset_name: \t {dataset_name}")


# 2.dataset_sizt: (10000 & 2000) or (1000, 200)
# def_dataset_size = dataset_size_type[0]                   # [10000, 2000]
def_dataset_size = dataset_size_type[1]                   # [1000, 200]
print(f"\n def_dataset_size: train: {def_dataset_size[0]}, \t test: {def_dataset_size[1]}")


# 3.batch_size: '32', '64' or '128'
batch_Size = batch_size_type[0]                           # 32
# batch_Size = batch_size_type[1]                           # 64
# batch_Size = batch_size_type[2]                           # 128
print(f"\n batch_Size: \t {batch_Size}")


# 4.type of dataset-split: "norm_subject_independed" or "norm_random"
def_dataset = dataset_type[0]                             # norm_subject
# def_dataset = dataset_type[1]                             # norm_random
print(f"\n def_dataset: \t {def_dataset}")


# 5.learning_rate: '1e-3', '1e-4', '1e-5' or '1e-6'
lr_type = [1e-3, 1e-4, 1e-5, 1e-6] 
# learning_rate = lr_type[0]                                # 1e-3
learning_rate = lr_type[1]                                # 1e-4
# learning_rate = lr_type[2]                                # 1e-5
# learning_rate = lr_type[3]                                # 1e-6
print(f"\n learning_rate: \t {learning_rate}")


# 6.number of epochs: 1, 2, 10, 25 or 500
epochs = epochs_num[-1]                                   # 500
print(f"\n epochs: \t {epochs}")




weight_Decay = 1e-5

active_func = None

patience = 3               # after 3 Epochen without Optimierung has to stop training
print(f"\n patience: \t {patience}")



 dataset_name: 	 norm_labels.csv

 def_dataset_size: train: 1000, 	 test: 200

 batch_Size: 	 32

 def_dataset: 	 norm_subject

 learning_rate: 	 0.0001

 epochs: 	 500

 patience: 	 3


In [ ]:
# name_dataset_type = ['norm_labels.csv', 'labels.csv']
# dataset_size_type = [[10000, 2000], [1000, 200]]
# dataset_type = ["norm_subject", "norm_random"]
# batch_size_type = [32, 64, 128]
# lr_type = [1e-3, 1e-4, 1e-5, 1e-6] 
# epochs_num = [1, 2, 10, 25, 500]

# optimizer_name = "AdamW"

# # ##########################################################################
# # 1.type Dataset: 'norm_labels.csv' or 'labels.csv'
# dataset_name = name_dataset_type[0]                       # norm_labels.csv
# # dataset_name = name_dataset_type[1]                       # labels.csv

# # 2.dataset_sizt: (10000 & 2000) or (1000, 200)
# # def_dataset_size = dataset_size_type[0]                   # [10000, 2000]
# def_dataset_size = dataset_size_type[1]                   # [1000, 200]

# # 3.batch_size: '32', '64' or '128'
# # batch_Size = batch_size_type[0]                           # 32
# # batch_Size = batch_size_type[1]                           # 64
# batch_Size = batch_size_type[2]                           # 128

# # 4.type of dataset-split: "norm_subject_independed" or "norm_random"
# def_dataset = dataset_type[0]                             # norm_subject
# # def_dataset = dataset_type[1]                             # norm_random

# # 5.learning_rate: '1e-3', '1e-4', '1e-5' or '1e-6'
# lr_type = [1e-3, 1e-4, 1e-5, 1e-6] 
# learning_rate = lr_type[0]                                # 1e-3
# # learning_rate = lr_type[1]                                # 1e-4
# # learning_rate = lr_type[2]                                # 1e-5
# # learning_rate = lr_type[3]                                # 1e-6

# epochs = epochs_num[-1]                                   # 500

# weight_Decay = 1e-5
# active_func = None
# patience = 3               # after 3 Epochen without Optimierung has to stop training

In [37]:
# 6: CSV laden
root_folder = "./dataset"
csv_path = Path(f"{root_folder}/{dataset_name}")
# print(f"\n csv_path: {csv_path}")

df = pd.read_csv(csv_path)
df.head()
# check:
# print(df.shape)

,image_name,x,y,subject_ID,screen_w,screen_h
0,dataset/images/00002/00002/frames/00000.jpg,0.500000,0.500000,2,320,568
1,dataset/images/00002/00002/frames/00001.jpg,0.500000,0.500000,2,320,568
2,dataset/images/00002/00002/frames/00002.jpg,0.500000,0.500000,2,320,568
3,dataset/images/00002/00002/frames/00003.jpg,0.500000,0.500000,2,320,568
4,dataset/images/00002/00002/frames/00004.jpg,0.873929,0.114375,2,320,568


In [38]:
# 8: DataLoader
# Transformationen:
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    
    transforms.ColorJitter(
        brightness=0.3,
        contrast=0.3,
        saturation=0.2
    ),

    transforms.RandomGrayscale(p=0.05),

    transforms.GaussianBlur(
        kernel_size=3,
        sigma=(0.1,1.5)
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


# Dataset:


if def_dataset == 'norm_subject':

    train_dataset = GazeDataset(
        "./splits/norm_subject_train.csv",
        transform, dataset_size=def_dataset_size[0],
    )
    
    test_dataset = GazeDataset(
        "./splits/norm_subject_test.csv",
        transform, dataset_size=def_dataset_size[1],
    )



elif def_dataset == 'norm_random':

    train_dataset = GazeDataset(
        "./splits/norm_random_train.csv",
        transform, dataset_size=def_dataset_size[0],
    )
    
    test_dataset = GazeDataset(
        "./splits/norm_random_test.csv",
        transform, dataset_size=def_dataset_size[1],
    )

else:

    raise ValueError(
                "The input as dataset_type is Wrong!"
            )


# Loader:
train_loader = DataLoader(
    train_dataset,
    batch_size=batch_Size,
    shuffle=True,
    num_workers=8,
    persistent_workers=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_Size,
    shuffle=False,
    num_workers=8,
    persistent_workers=True
)

100%|██████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:02<00:00, 98.58it/s]


In [39]:
# 9: ResNet18 (Pretrainiertes Modell):
# Load:
def reset_model(act=None):
    model = resnet18(
        weights=ResNet18_Weights.DEFAULT
    )

    model_name = model.__class__.__name__
    
    # ---------------------------------------
    # Activation function for the last layer
    # ---------------------------------------
    if act == "Sigmoid":
        last_layer = nn.Sigmoid()

    elif act == "Gaussian":
        last_layer = GaussianActivation(sigma=1.0)

    elif act == "ReLU":
        last_layer = nn.ReLU()

    elif act == "None":
        last_layer = nn.Identity()

    else:
        raise ValueError(
            f"Unknown activation function: {act}"
        )

    # ---------------------------------------
    # Replace original ResNet FC
    # ---------------------------------------
    model.fc = nn.Sequential(
        nn.Linear(
            model.fc.in_features,
            512
        ),
        nn.ReLU(),

        nn.Linear(
            512,
            256
        ),
        nn.ReLU(),

        nn.Dropout(0.2),

        nn.Linear(
            256,
            128
        ),
        nn.ReLU(),

        nn.Linear(
            128,
            2
        ),

        # Last activation
        last_layer
    )

    return model, model_name

In [40]:
# 10: GPU or CPU
# check:
device = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

In [32]:

print(f"\n\t dataset_name: \t {dataset_name}")
print(f"\t def_dataset_size: train: {def_dataset_size[0]}, \t test: {def_dataset_size[1]}")
print(f"\t batch_Size: \t {batch_Size}")
print(f"\t def_dataset: \t {def_dataset}")
print(f"\t learning_rate: \t {learning_rate}")
print(f"\t epochs: \t {epochs}")
print(f"\t patience: \t {patience}")



parm1, parm2 = [], []

parm_test_error = []
parm_run_time = []




criterion = nn.L1Loss()

criterion_base = nn.L1Loss()

epochs = epochs

if globals().get("bas_const_err") is None:
    bas_const_err = 27.245

if globals().get("bas_rand_err") is None:
    bas_rand_err = 38.961
    

model_output = './models/best_models'
model_dir= Path(model_output)

if not os.path.exists(model_dir):
    model_dir.mkdir(
        parents=True,
        exist_ok=True
    )


diagrams_output = './results/best_diagrams'
diagrams_dir= Path(diagrams_output)

if not os.path.exists(diagrams_dir):
    diagrams_dir.mkdir(
        parents=True,
        exist_ok=True
    )

diag_test_errors = {}
diag_train_errors = {}


act_time_epochs = {}


diag_test_error, diag_train_error = [], []

acts = ['Sigmoid', 'Gaussian', 'ReLU', 'None']

act = acts[0]

# for act in ['Sigmoid', 'Gaussian', 'ReLU', 'None']:
# for act in ['Sigmoid']:
# for act in ['None']:

if act == 'Sigmoid':

    train_start = time.perf_counter()
  
    model, model_name = reset_model(act=act)

    active_func = act

    diag_test_errors[act] = []
    diag_train_errors[act] = []

    best_error = float("inf")

    t = 0                      # Number Epochen without Optimierung
    e = 0                      # Number Epochen with Optimierung


    model.to(device)



    for param in model.parameters():
        param.requires_grad = False

    # Unfreeze the head
    for param in model.layer4.parameters():
        param.requires_grad=False

    for param in model.fc.parameters():
        param.requires_grad=True

    optimizer = torch.optim.AdamW(
        filter(lambda p:p.requires_grad, model.parameters()),
        lr=learning_rate,
        weight_decay=weight_Decay
    )

    print('\n ',"=#=" * 25)
    print(f"\t\t act: {act}")
    print(' ',"=#=" * 25)

    print("\n\t Start: \n")
    
    print("train_error:")
    train_mae, train_rmse, train_diag_pct = diagonal_errors(model, train_loader, device)
    diag_train_error.append(np.round(train_diag_pct, 4))
    
    diag_train_errors[act].append(np.round(train_diag_pct, 4))



    print("\ntest_error:")
    test_mae, test_rmse, test_diag_pct = diagonal_errors(model, test_loader, device)
    diag_test_error.append(np.round(test_diag_pct, 4))

    diag_test_errors[act].append(np.round(test_diag_pct, 4))

    if best_error is None or test_diag_pct < best_error:    
        # set the first test-error
        best_error = test_diag_pct
        t = 0
        e += 1


    print("\n\n\t Training: \n")

    for epoch in range(epochs):

        epoch_start = time.perf_counter()

        model.train()
        running_loss = 0

        loop = tqdm(
            train_loader,
            desc=f"Epoch {epoch + 1}"
        )

        for images, targets in loop:
            images = images.to(device)
            targets = targets.to(device)
            optimizer.zero_grad()
            preds = model(images)

            ################################
            
            # Loss 1:
            loss = criterion(
                preds,
                targets
            )

            
            # Loss 2: 
            # loss = sensitive_loss(
            #     preds,
            #     targets
            # )
            
            ################################

            loss.backward()
            optimizer.step()
            running_loss += loss.item()

            loop.set_postfix(
                loss=loss.item()
            )

        # epoch_end = time.perf_counter()

        print(f"\ntrain_error:")
        train_mae, train_rmse, train_diag_pct = diagonal_errors(model, train_loader, device)
        diag_train_error.append(np.round(train_diag_pct, 4))

        diag_train_errors[act].append(np.round(train_diag_pct, 4))

        print(f"\ntest_error:")
        test_mae, test_rmse, test_diag_pct = diagonal_errors(model, test_loader, device)
        diag_test_error.append(np.round(test_diag_pct, 4))

        diag_test_errors[act].append(np.round(test_diag_pct, 4))

        # --------------------------------------------------
        # Early Stopping
        # --------------------------------------------------
        
        if best_error is None or test_diag_pct < best_error:
        
            # find an improvement
            best_error = test_diag_pct
            t = 0
            e += 1
        
            print(
                f"Test-Diagonal-Error: {test_diag_pct:.4f}% | "
                f"Improvment: {e}"
            )
        
            # save the better Modell
            torch.save(
                model.state_dict(),
                f"./models/best_models/"
                f"best_{model_name}_{act}.path"
            )

            
            # torch.save(
            #     model.state_dict(),
            #     f"./models/best_optim-model_"
            #     f"{def_dataset}_{def_dataset_size[0]}-{def_dataset_size[1]}.path"
            # )

        
        else:
        
            # without imporovement
            t += 1
        
            print(
                f"Patience: {t}/{patience}"
            )
        
            if t >= patience:
                print(
                    f"\nEarly Stopping after {epoch + 1} Epochen."
                )
                print(
                    f"Imporovments totally: {e}"
                )
                break



        epoch_end = time.perf_counter()


        print(
            f"\n[{datetime.now().strftime('%H:%M:%S')}] Epoch {epoch + 1}: {epoch_end - epoch_start:.2f} Sekunden | "
            f"Running_loss: {running_loss / len(train_loader):.3f} | "
            f"test_diag_error={test_diag_pct:.4f}% | "
            f"train_diag_error={train_diag_pct:.4f}% | \n"
        )

        # torch.save(model.state_dict(),
        #         f"./models/last_best_optim_model_{def_dataset}_{def_dataset_size[0]}-{def_dataset_size[1]}.path")

        torch.save(
                model.state_dict(),
                f"./models/best_models/"
                f"last_{model_name}_{act}.path"
            )


    train_end = time.perf_counter()


    elapsed_running_time = train_end - train_start
    print(f"\ntotll running-tiems (s): {elapsed_running_time:.2f} Sekunden")
    print(f"totll running-tiems (min): {elapsed_running_time / 60:.2f} Minuten\n")


    act_time_epochs[act] = {
        "time_minutes": elapsed_running_time / 60,
        "epochs": epoch + 1,
        "improvements": e,
        "best_test_error": best_error
    }


    parm1.append(best_error)
    parm2.append(elapsed_running_time / 60)

print(f"\n\n Parameter:\n best_test_error: {np.float64(parm1)}, \n running_time: {np.float64(parm2)} \n")





	 dataset_name: 	 norm_labels.csv
	 def_dataset_size: train: 1000, 	 test: 200
	 batch_Size: 	 32
	 def_dataset: 	 norm_subject
	 learning_rate: 	 0.0001
	 epochs: 	 500
	 patience: 	 3
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.fc.parameters: True
param in model.fc.parameters: True
param in model.fc.parameters: True
param in model.fc.parameters: True
param in model.fc.parameters: True
param in model.fc.parameters: True
par

Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [00:47<00:00,  1.50s/it, loss=0.211]



train_error:
MAE : 0.2291 	 RMSE: 0.2766 
Diagonal-Error %: 19.5593 %

test_error:
MAE : 0.2364 	 RMSE: 0.2843 
Diagonal-Error %: 20.1041 %
Test-Diagonal-Error: 20.1041% | Improvment: 2

[13:49:36] Epoch 1: 105.75 Sekunden | Running_loss: 0.231 | test_diag_error=20.1041% | train_diag_error=19.5593% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [00:51<00:00,  1.61s/it, loss=0.261]



train_error:
MAE : 0.2264 	 RMSE: 0.2743 
Diagonal-Error %: 19.3963 %

test_error:
MAE : 0.2413 	 RMSE: 0.2885 
Diagonal-Error %: 20.4009 %
Patience: 1/3

[13:51:27] Epoch 2: 110.78 Sekunden | Running_loss: 0.230 | test_diag_error=20.4009% | train_diag_error=19.3963% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [00:53<00:00,  1.67s/it, loss=0.204]



train_error:
MAE : 0.2243 	 RMSE: 0.2724 
Diagonal-Error %: 19.2643 %

test_error:
MAE : 0.2440 	 RMSE: 0.2909 
Diagonal-Error %: 20.5724 %
Patience: 2/3

[13:53:23] Epoch 3: 115.92 Sekunden | Running_loss: 0.226 | test_diag_error=20.5724% | train_diag_error=19.2643% | 



Epoch 4: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:04<00:00,  2.03s/it, loss=0.222]



train_error:
MAE : 0.2229 	 RMSE: 0.2722 
Diagonal-Error %: 19.2453 %

test_error:
MAE : 0.2547 	 RMSE: 0.3029 
Diagonal-Error %: 21.4151 %
Patience: 3/3

Early Stopping after 4 Epochen.
Imporovments totally: 2

totll running-tiems (s): 519.24 Sekunden
totll running-tiems (min): 8.65 Minuten



 Parameter:
 best_test_error: [20.10409], 
 running_time: [8.65406785] 



In [33]:
for act, values in act_time_epochs.items():
    print(
        f"last_layer: {act}\t"
        f" epochs: {values['epochs']} Epochen\t|"
        f" running_time: {values['time_minutes']:.2f} min\t |"
        f" improvements: {values['improvements']} Epochen\t |"
        f" best_test_error: {values['best_test_error']:.4f} % "
    )

last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 8.65 min	 | improvements: 2 Epochen	 | best_test_error: 20.1041 % 


In [ ]:

print(f"\n\n Diagonal-Train-Error: {np.float64(diag_train_error)}\n")
print(f" Diagonal-Test-Error: {np.float64(diag_test_error)}\n\n")

print(f" Diagonal-Train-Error-Max: {np.max(diag_train_error)} \t Diagonal-Train-Error-Min: {np.min(diag_train_error)}\t")
# print(f" Diagonal-Train-Error-Ave: {np.mean(diag_train_error)}\n")

print(f" Diagonal-Test-Error-Max: {np.max(diag_test_error)}\t Diagonal-Test-Error-Min: {np.min(diag_test_error)}\t max_needed_epochs: {e+2}\n\n")
# print(f" Diagonal-Test-Error-Ave: {np.mean(diag_test_error)}\n")


if globals().get("bas_const_err") is None:
    bas_const_err = 27.245

if globals().get("bas_rand_err") is None:
    bas_rand_err = 38.961


# Curven:

# Minimum Test Error bestimmen
min_test_error = min(diag_test_error)
min_test_epoch = diag_test_error.index(min_test_error) + 1

# Die vier Werte an dieser Epoch
train_at_min = diag_train_error[min_test_epoch - 1]
test_at_min = diag_test_error[min_test_epoch - 1]
const_at_min = bas_const_err
rand_at_min = bas_rand_err

# Die Farbe
train_color = "tab:blue"
test_color = "tab:orange"
const_color = "tab:green"
rand_color = "tab:red"
point_color = "black"

# Epochs beginnen bei 1
epochs = range(1, len(diag_test_error) + 1)
# epochs = range(0, len(diag_test_error) + 1)

plt.figure(figsize=(10, 7))

# Train Error
plt.plot(epochs, diag_train_error, label="Train", linewidth=2, color=train_color)


# Test Error
plt.plot(epochs, diag_test_error, label="Test", linewidth=2, color=test_color)


# Vertikale Linie durch alle vier Kurven
plt.axvline(
    x=min_test_epoch,
    linestyle="--",
    linewidth=1.2,
    alpha=0.7,
    # label=f"Min Test Error (Epoch {min_test_epoch})"
)

# Punkt beim Minimum des Test Errors
plt.scatter(
    min_test_epoch,
    min_test_error,
    s=40,
    zorder=5,
    color=point_color
    # label=f"Min Test Error ({min_test_error:.2f}%)"
)

plt.scatter(
    min_test_epoch,
    train_at_min,
    s=40,
    zorder=5,
    color=point_color
    # label=f"Train at min_Test_Error ({train_at_min_test:.2f}%)"
)

# Werte an der vertikalen Linie anzeigen
plt.annotate(
    f"'Train': {train_at_min:.3f}%",
    xy=(min_test_epoch, train_at_min),
    xytext=(8, 10),
    textcoords="offset points",
    color=train_color,
    fontsize=8
)

plt.annotate(
    f"'Test': {test_at_min:.3f}%",
    xy=(min_test_epoch, test_at_min),
    xytext=(8, -10),
    textcoords="offset points",
    color=test_color,
    fontsize=8,
)


plt.title("Train- vs. Test-Error:")
plt.xlabel("Epoche")
plt.ylabel("Diagnostic Error (%)")

plt.xticks(epochs)

plt.grid(True, alpha=0.3, linewidth=0.6)
plt.legend()



# ===================================================
# =============== all 4 Diagrams ====================
# ===================================================


plt.figure(figsize=(10, 7))


# Train Error
plt.plot(
    epochs,
    diag_train_error,
    label="Train",
    linewidth=2,
    color=train_color
)


# Test Error
plt.plot(
    epochs,
    diag_test_error,
    label="Test",
    linewidth=2,
    color=test_color
)


# Constant Baseline
plt.plot(
    epochs,
    [bas_const_err] * len(epochs),
    label="Constant Error",
    linestyle="--",
    linewidth=1.2,
    alpha=0.6,
    color=const_color
)


# Random Baseline
plt.plot(
    epochs,
    [bas_rand_err] * len(epochs),
    label="Random Error",
    linestyle="-.",
    linewidth=1.2,
    alpha=0.6,
    color=rand_color
)



print(f"\nMinimum Test Error:")
print(f"Epoch:           {min_test_epoch}")
print(f"Test Error:      {test_at_min:.4f}%")
print(f"Train Error:     {train_at_min:.4f}%")
print(f"Constant Error:  {bas_const_err:.4f}%")
print(f"Random Error:    {bas_rand_err:.4f}%\n")


# Punkt beim Minimum des Test Errors
plt.scatter(
    min_test_epoch,
    min_test_error,
    s=40,
    zorder=5,
    color=point_color
    # label=f"Min Test Error ({min_test_error:.2f}%)"
)

plt.scatter(
    min_test_epoch,
    train_at_min,
    s=40,
    zorder=5,
    color=point_color
    # label=f"Train at min_Test_Error ({train_at_min_test:.2f}%)"
)

plt.scatter(
    min_test_epoch,
    const_at_min,
    s=20,
    zorder=4,
    color=point_color
)

plt.scatter(
    min_test_epoch,
    rand_at_min,
    s=20,
    zorder=4,
    color=point_color
)


# Vertikale Linie durch alle vier Kurven
plt.axvline(
    x=min_test_epoch,
    linestyle="--",
    linewidth=1.2,
    alpha=0.7,
    # label=f"Min Test Error (Epoch {min_test_epoch})"
)

# Werte an der vertikalen Linie anzeigen
plt.annotate(
    f"'Train': {train_at_min:.3f}%",
    xy=(min_test_epoch, train_at_min),
    xytext=(5, 5),
    textcoords="offset points",
    color=train_color,
    fontsize=8
)

plt.annotate(
    f"'Test': {test_at_min:.3f}%",
    xy=(min_test_epoch, test_at_min),
    xytext=(5, 7),
    textcoords="offset points",
    color=test_color,
    fontsize=8
)

plt.annotate(
    f"'Constant': {const_at_min:.3f}%",
    xy=(min_test_epoch, const_at_min),
    xytext=(5, 10),
    textcoords="offset points",
    color=const_color,
    fontsize=7
)

plt.annotate(
    f"'Random': {rand_at_min:.3f}%",
    xy=(min_test_epoch, rand_at_min),
    xytext=(5, -15),
    textcoords="offset points",
    color=rand_color,
    fontsize=7
)

# Titel
plt.title(
    f"{def_dataset} "
    f"(train:{def_dataset_size[0]}, test:{def_dataset_size[1]})\n"
    f"lr = {learning_rate} | "
    f"{elapsed_running_time / 60:.2f} Minuten | "
    f"extra_act_fun: {active_func} | "
    f"epochs_improvements_totally: {e + 2}"
)
# plt.title(f"{def_dataset}((train:{def_dataset_size[0]}, test:{def_dataset_size[1]})) \n" 
#           f" lr = {learning_rate} | {elapsed_running_time/60:.2f} Minuten | extra_act_fun: {active_func} | epochs_imporovments_totally: {e+2}"
# )

plt.xlabel("Epoche")
plt.ylabel("Diagnostic Error (%)")

plt.xticks(epochs)

# plt.xticks(range(1, len(epochs) + 1, 1))
# plt.yticks(range(0, 51, 5))

plt.grid(True, alpha=0.4)
plt.legend()

# Ordner erstellen (falls er noch nicht existiert)
os.makedirs("./results", exist_ok=True)

# Diagramm speichern
plt.savefig(
    f"results/diag_error_{def_dataset}_{learning_rate}_{def_dataset_size[0]}_{def_dataset_size[1]}_a.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

In [ ]:

    
    
print(f"\n\t dataset_name: \t {dataset_name}")
print(f"\t def_dataset_size: train: {def_dataset_size[0]}, \t test: {def_dataset_size[1]}")
print(f"\t batch_Size: \t {batch_Size}")
print(f"\t def_dataset: \t {def_dataset}")
print(f"\t learning_rate: \t {learning_rate}")
print(f"\t epochs: \t {epochs}")
print(f"\t patience: \t {patience}")


    
parm1, parm2 = [], []

parm_test_error = []
parm_run_time = []


criterion = nn.L1Loss()

criterion_base = nn.L1Loss()

epochs = epochs

if globals().get("bas_const_err") is None:
    bas_const_err = 30.987 

if globals().get("bas_rand_err") is None:
    bas_rand_err  = 42.702 
    


diag_test_errors = {}
diag_train_errors = {}


act_time_epochs = {}


diag_test_error, diag_train_error = [], []

acts = ['Sigmoid', 'Gaussian', 'ReLU', 'None']

for i in range(len(acts)):

    act = acts[i]
    
    for t in range(5):
        
        print(f"\n\t t: {t + 1}")
        

        
        
        train_start = time.perf_counter()
      
        model, model_name = reset_model(act=act)
    
        active_func = act
    
        diag_test_errors[act] = []
        diag_train_errors[act] = []
    
        best_error = float("inf")
    
        t = 0                      # Number Epochen without Optimierung
        e = 0                      # Number Epochen with Optimierung
    
    
        model.to(device)
    
    
    
        for param in model.parameters():
            param.requires_grad = False
    
        # Unfreeze the head
        for param in model.layer4.parameters():
            param.requires_grad=True
    
        for param in model.fc.parameters():
            param.requires_grad=True
    
    
        optimizer = torch.optim.AdamW(
            filter(lambda p:p.requires_grad, model.parameters()),
            lr=learning_rate,
            weight_decay=weight_Decay
        )
    
        print('\n ',"=#=" * 25)
        print(f"\t\t act: {act}")
        print(' ',"=#=" * 25)
    
        print("\n\t Start: \n")
        
        print("train_error:")
        train_mae, train_rmse, train_diag_pct = diagonal_errors(model, train_loader, device)
        diag_train_error.append(np.round(train_diag_pct, 4))
        
        diag_train_errors[act].append(np.round(train_diag_pct, 4))
    
    
    
        print("\ntest_error:")
        test_mae, test_rmse, test_diag_pct = diagonal_errors(model, test_loader, device)
        diag_test_error.append(np.round(test_diag_pct, 4))
    
        diag_test_errors[act].append(np.round(test_diag_pct, 4))

        if best_error is None or test_diag_pct < best_error:    
            # set the first test-error
            best_error = test_diag_pct
            t = 0
            e += 1
    
    
        print("\n\n\t Training: \n")
    
        for epoch in range(epochs):
    
            epoch_start = time.perf_counter()
    
            model.train()
            running_loss = 0
    
            loop = tqdm(
                train_loader,
                desc=f"Epoch {epoch + 1}"
            )
    
            for images, targets in loop:
                images = images.to(device)
                targets = targets.to(device)
                optimizer.zero_grad()
                preds = model(images)
    
                ################################
                
                # Loss 1:
                loss = criterion(
                    preds,
                    targets
                )
    
                
                ################################
    
                loss.backward()
                optimizer.step()
                running_loss += loss.item()
    
                loop.set_postfix(
                    loss=loss.item()
                )
    
            # epoch_end = time.perf_counter()
    
            print(f"\ntrain_error:")
            train_mae, train_rmse, train_diag_pct = diagonal_errors(model, train_loader, device)
            diag_train_error.append(np.round(train_diag_pct, 4))
    
            diag_train_errors[act].append(np.round(train_diag_pct, 4))
    
            print(f"\ntest_error:")
            test_mae, test_rmse, test_diag_pct = diagonal_errors(model, test_loader, device)
            diag_test_error.append(np.round(test_diag_pct, 4))
    
            diag_test_errors[act].append(np.round(test_diag_pct, 4))
    
            # --------------------------------------------------
            # Early Stopping
            # --------------------------------------------------
            
            if best_error is None or test_diag_pct < best_error:
            
                # find an improvement
                best_error = test_diag_pct
                t = 0
                e += 1
            
                print(
                    f"Test-Diagonal-Error: {test_diag_pct:.4f}% | "
                    f"Improvment: {e}"
                )
            
            
            else:
            
                # without imporovement
                t += 1
            
                print(
                    f"Patience: {t}/{patience}"
                )
            
                if t >= patience:
                    print(
                        f"\nEarly Stopping after {epoch + 1} Epochen."
                    )
                    print(
                        f"Imporovments totally: {e}"
                    )
                    break
    
    
    
            epoch_end = time.perf_counter()
    
    
            print(
                f"\n[{datetime.now().strftime('%H:%M:%S')}] Epoch {epoch + 1}: {epoch_end - epoch_start:.2f} Sekunden | "
                f"Running_loss: {running_loss / len(train_loader):.3f} | "
                f"test_diag_error={test_diag_pct:.4f}% | "
                f"train_diag_error={train_diag_pct:.4f}% | \n"
            )
    
    
        train_end = time.perf_counter()
    
    
        elapsed_running_time = train_end - train_start
        print(f"\ntotll running-tiems (s): {elapsed_running_time:.2f} Sekunden")
        print(f"totll running-tiems (min): {elapsed_running_time / 60:.2f} Minuten\n")
    
    
        act_time_epochs[act] = {
            "time_minutes": elapsed_running_time / 60,
            "epochs": epoch + 1,
            "improvements": e,
            "best_test_error": best_error
        }
    
    
        parm1.append(best_error)
        parm2.append(elapsed_running_time / 60)

    
    
    
        for act, values in act_time_epochs.items():
            print(
                f"last_layer: {act}\t"
                f" epochs: {values['epochs']} Epochen\t|"
                f" running_time: {values['time_minutes']:.2f} min\t |"
                f" improvements: {values['improvements']} Epochen\t |"
                f" best_test_error: {values['best_test_error']:.4f} % "
            )

    
    print('\n ',"=#=" * 25)
    print(' ',"=#=" * 25)
    

    print(f"\n\n Parameter:\n best_test_error: {np.float64(parm1)}, \n running_time: {np.float64(parm2)} \n")



	 dataset_name: 	 norm_labels.csv
	 def_dataset_size: train: 1000, 	 test: 200
	 batch_Size: 	 32
	 def_dataset: 	 norm_subject
	 learning_rate: 	 0.0001
	 epochs: 	 500
	 patience: 	 3

	 t: 1

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: Sigmoid
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.2318 	 RMSE: 0.2792 
Diagonal-Error %: 19.7432 %

test_error:
MAE : 0.2347 	 RMSE: 0.2829 
Diagonal-Error %: 20.0008 %


	 Training: 



Epoch 1: 100%|████████████████████████████████████████████████████████████████████████| 32/32 [01:20<00:00,  2.51s/it, loss=0.32]



train_error:
MAE : 0.2200 	 RMSE: 0.2684 
Diagonal-Error %: 18.9759 %

test_error:
MAE : 0.2433 	 RMSE: 0.2904 
Diagonal-Error %: 20.5309 %
Patience: 1/3

[14:26:36] Epoch 1: 135.42 Sekunden | Running_loss: 0.230 | test_diag_error=20.5309% | train_diag_error=18.9759% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:08<00:00,  2.13s/it, loss=0.168]



train_error:
MAE : 0.2033 	 RMSE: 0.2577 
Diagonal-Error %: 18.2199 %

test_error:
MAE : 0.2559 	 RMSE: 0.3047 
Diagonal-Error %: 21.5451 %
Patience: 2/3

[14:28:39] Epoch 2: 123.21 Sekunden | Running_loss: 0.216 | test_diag_error=21.5451% | train_diag_error=18.2199% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:11<00:00,  2.23s/it, loss=0.238]



train_error:
MAE : 0.1885 	 RMSE: 0.2461 
Diagonal-Error %: 17.4019 %

test_error:
MAE : 0.2654 	 RMSE: 0.3166 
Diagonal-Error %: 22.3844 %
Patience: 3/3

Early Stopping after 3 Epochen.
Imporovments totally: 1

totll running-tiems (s): 455.64 Sekunden
totll running-tiems (min): 7.59 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.59 min	 | improvements: 1 Epochen	 | best_test_error: 20.0008 % 

	 t: 2

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: Sigmoid
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.2317 	 RMSE: 0.2805 
Diagonal-Error %: 19.8331 %

test_error:
MAE : 0.2356 	 RMSE: 0.2838 
Diagonal-Error %: 20.0648 %


	 Training: 



Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:09<00:00,  2.17s/it, loss=0.149]



train_error:
MAE : 0.2201 	 RMSE: 0.2700 
Diagonal-Error %: 19.0904 %

test_error:
MAE : 0.2494 	 RMSE: 0.2969 
Diagonal-Error %: 20.9940 %
Patience: 1/3

[14:33:49] Epoch 1: 124.96 Sekunden | Running_loss: 0.226 | test_diag_error=20.9940% | train_diag_error=19.0904% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:04<00:00,  2.01s/it, loss=0.157]



train_error:
MAE : 0.2049 	 RMSE: 0.2570 
Diagonal-Error %: 18.1742 %

test_error:
MAE : 0.2484 	 RMSE: 0.2933 
Diagonal-Error %: 20.7396 %
Patience: 2/3

[14:35:49] Epoch 2: 119.55 Sekunden | Running_loss: 0.217 | test_diag_error=20.7396% | train_diag_error=18.1742% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:06<00:00,  2.08s/it, loss=0.156]



train_error:
MAE : 0.1803 	 RMSE: 0.2326 
Diagonal-Error %: 16.4497 %

test_error:
MAE : 0.2560 	 RMSE: 0.3047 
Diagonal-Error %: 21.5484 %
Patience: 3/3

Early Stopping after 3 Epochen.
Imporovments totally: 1

totll running-tiems (s): 420.16 Sekunden
totll running-tiems (min): 7.00 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.00 min	 | improvements: 1 Epochen	 | best_test_error: 20.0648 % 

	 t: 3

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: Sigmoid
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.2339 	 RMSE: 0.2818 
Diagonal-Error %: 19.9283 %

test_error:
MAE : 0.2395 	 RMSE: 0.2872 
Diagonal-Error %: 20.3106 %


	 Training: 



Epoch 1: 100%|████████████████████████████████████████████████████████████████████████| 32/32 [01:10<00:00,  2.19s/it, loss=0.19]



train_error:
MAE : 0.2200 	 RMSE: 0.2683 
Diagonal-Error %: 18.9683 %

test_error:
MAE : 0.2434 	 RMSE: 0.2901 
Diagonal-Error %: 20.5161 %
Patience: 1/3

[14:41:02] Epoch 1: 128.81 Sekunden | Running_loss: 0.228 | test_diag_error=20.5161% | train_diag_error=18.9683% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:10<00:00,  2.21s/it, loss=0.155]



train_error:
MAE : 0.2042 	 RMSE: 0.2557 
Diagonal-Error %: 18.0813 %

test_error:
MAE : 0.2579 	 RMSE: 0.3057 
Diagonal-Error %: 21.6194 %
Patience: 2/3

[14:43:11] Epoch 2: 128.39 Sekunden | Running_loss: 0.217 | test_diag_error=21.6194% | train_diag_error=18.0813% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:09<00:00,  2.16s/it, loss=0.153]



train_error:
MAE : 0.1778 	 RMSE: 0.2317 
Diagonal-Error %: 16.3844 %

test_error:
MAE : 0.2640 	 RMSE: 0.3135 
Diagonal-Error %: 22.1705 %
Patience: 3/3

Early Stopping after 3 Epochen.
Imporovments totally: 1

totll running-tiems (s): 447.80 Sekunden
totll running-tiems (min): 7.46 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.46 min	 | improvements: 1 Epochen	 | best_test_error: 20.3106 % 

	 t: 4

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: Sigmoid
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.2349 	 RMSE: 0.2826 
Diagonal-Error %: 19.9811 %

test_error:
MAE : 0.2411 	 RMSE: 0.2885 
Diagonal-Error %: 20.3969 %


	 Training: 



Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:03<00:00,  1.99s/it, loss=0.276]



train_error:
MAE : 0.2199 	 RMSE: 0.2684 
Diagonal-Error %: 18.9792 %

test_error:
MAE : 0.2396 	 RMSE: 0.2868 
Diagonal-Error %: 20.2817 %
Test-Diagonal-Error: 20.2817% | Improvment: 2

[14:48:09] Epoch 1: 116.67 Sekunden | Running_loss: 0.230 | test_diag_error=20.2817% | train_diag_error=18.9792% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:02<00:00,  1.95s/it, loss=0.292]



train_error:
MAE : 0.1955 	 RMSE: 0.2486 
Diagonal-Error %: 17.5809 %

test_error:
MAE : 0.2501 	 RMSE: 0.2971 
Diagonal-Error %: 21.0097 %
Patience: 1/3

[14:50:07] Epoch 2: 117.17 Sekunden | Running_loss: 0.217 | test_diag_error=21.0097% | train_diag_error=17.5809% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:02<00:00,  1.95s/it, loss=0.224]



train_error:
MAE : 0.1710 	 RMSE: 0.2221 
Diagonal-Error %: 15.7029 %

test_error:
MAE : 0.2526 	 RMSE: 0.3007 
Diagonal-Error %: 21.2633 %
Patience: 2/3

[14:52:03] Epoch 3: 116.58 Sekunden | Running_loss: 0.192 | test_diag_error=21.2633% | train_diag_error=15.7029% | 



Epoch 4: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:01<00:00,  1.93s/it, loss=0.144]



train_error:
MAE : 0.1555 	 RMSE: 0.2085 
Diagonal-Error %: 14.7436 %

test_error:
MAE : 0.2584 	 RMSE: 0.3067 
Diagonal-Error %: 21.6904 %
Patience: 3/3

Early Stopping after 4 Epochen.
Imporovments totally: 2

totll running-tiems (s): 521.05 Sekunden
totll running-tiems (min): 8.68 Minuten

last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 8.68 min	 | improvements: 2 Epochen	 | best_test_error: 20.2817 % 

	 t: 5

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: Sigmoid
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.2313 	 RMSE: 0.2788 
Diagonal-Error %: 19.7128 %

test_error:
MAE : 0.2347 	 RMSE: 0.2824 
Diagonal-Error %: 19.9700 %


	 Training: 



Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:18<00:00,  2.46s/it, loss=0.239]



train_error:
MAE : 0.2205 	 RMSE: 0.2696 
Diagonal-Error %: 19.0608 %

test_error:
MAE : 0.2381 	 RMSE: 0.2859 
Diagonal-Error %: 20.2128 %
Patience: 1/3

[14:57:38] Epoch 1: 156.97 Sekunden | Running_loss: 0.229 | test_diag_error=20.2128% | train_diag_error=19.0608% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:07<00:00,  2.12s/it, loss=0.325]



train_error:
MAE : 0.1994 	 RMSE: 0.2519 
Diagonal-Error %: 17.8153 %

test_error:
MAE : 0.2448 	 RMSE: 0.2906 
Diagonal-Error %: 20.5474 %
Patience: 2/3

[14:59:44] Epoch 2: 126.60 Sekunden | Running_loss: 0.220 | test_diag_error=20.5474% | train_diag_error=17.8153% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:08<00:00,  2.13s/it, loss=0.207]



train_error:
MAE : 0.1782 	 RMSE: 0.2304 
Diagonal-Error %: 16.2904 %

test_error:
MAE : 0.2664 	 RMSE: 0.3163 
Diagonal-Error %: 22.3625 %
Patience: 3/3

Early Stopping after 3 Epochen.
Imporovments totally: 1

totll running-tiems (s): 471.72 Sekunden
totll running-tiems (min): 7.86 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.86 min	 | improvements: 1 Epochen	 | best_test_error: 19.9700 % 

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=


 Parameter:
 best_test_error: [20.00081 20.06476 20.31059 20.2817  19.97003], 
 running_time: [7.59391784 7.00269289 7.46341295 8.6842122  7.86201617] 


	 t: 1

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: Gaussian
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.5190 	 RMSE: 0.5893 
Diagonal-Error %: 41.6709 %

test_e

Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:07<00:00,  2.10s/it, loss=0.133]



train_error:
MAE : 0.2485 	 RMSE: 0.3132 
Diagonal-Error %: 22.1499 %

test_error:
MAE : 0.2897 	 RMSE: 0.3418 
Diagonal-Error %: 24.1675 %
Test-Diagonal-Error: 24.1675% | Improvment: 2

[15:04:49] Epoch 1: 124.88 Sekunden | Running_loss: 0.353 | test_diag_error=24.1675% | train_diag_error=22.1499% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:07<00:00,  2.12s/it, loss=0.201]



train_error:
MAE : 0.2061 	 RMSE: 0.2569 
Diagonal-Error %: 18.1670 %

test_error:
MAE : 0.2626 	 RMSE: 0.3122 
Diagonal-Error %: 22.0784 %
Test-Diagonal-Error: 22.0784% | Improvment: 3

[15:06:53] Epoch 2: 124.02 Sekunden | Running_loss: 0.225 | test_diag_error=22.0784% | train_diag_error=18.1670% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:07<00:00,  2.11s/it, loss=0.214]



train_error:
MAE : 0.1904 	 RMSE: 0.2459 
Diagonal-Error %: 17.3897 %

test_error:
MAE : 0.2682 	 RMSE: 0.3185 
Diagonal-Error %: 22.5218 %
Patience: 1/3

[15:08:58] Epoch 3: 124.35 Sekunden | Running_loss: 0.211 | test_diag_error=22.5218% | train_diag_error=17.3897% | 



Epoch 4: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:16<00:00,  2.39s/it, loss=0.189]



train_error:
MAE : 0.1781 	 RMSE: 0.2285 
Diagonal-Error %: 16.1595 %

test_error:
MAE : 0.2672 	 RMSE: 0.3171 
Diagonal-Error %: 22.4191 %
Patience: 2/3

[15:11:14] Epoch 4: 136.54 Sekunden | Running_loss: 0.201 | test_diag_error=22.4191% | train_diag_error=16.1595% | 



Epoch 5: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:06<00:00,  2.08s/it, loss=0.154]



train_error:
MAE : 0.2199 	 RMSE: 0.2933 
Diagonal-Error %: 20.7366 %

test_error:
MAE : 0.2458 	 RMSE: 0.2946 
Diagonal-Error %: 20.8302 %
Test-Diagonal-Error: 20.8302% | Improvment: 4

[15:13:17] Epoch 5: 122.82 Sekunden | Running_loss: 0.184 | test_diag_error=20.8302% | train_diag_error=20.7366% | 



Epoch 6: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:10<00:00,  2.22s/it, loss=0.221]



train_error:
MAE : 0.1659 	 RMSE: 0.2112 
Diagonal-Error %: 14.9306 %

test_error:
MAE : 0.2734 	 RMSE: 0.3247 
Diagonal-Error %: 22.9585 %
Patience: 1/3

[15:15:29] Epoch 6: 131.51 Sekunden | Running_loss: 0.189 | test_diag_error=22.9585% | train_diag_error=14.9306% | 



Epoch 7: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:12<00:00,  2.28s/it, loss=0.192]



train_error:
MAE : 0.1566 	 RMSE: 0.2020 
Diagonal-Error %: 14.2805 %

test_error:
MAE : 0.2813 	 RMSE: 0.3345 
Diagonal-Error %: 23.6521 %
Patience: 2/3

[15:17:39] Epoch 7: 130.29 Sekunden | Running_loss: 0.167 | test_diag_error=23.6521% | train_diag_error=14.2805% | 



Epoch 8: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:05<00:00,  2.06s/it, loss=0.163]



train_error:
MAE : 0.1523 	 RMSE: 0.1967 
Diagonal-Error %: 13.9055 %

test_error:
MAE : 0.3223 	 RMSE: 0.3916 
Diagonal-Error %: 27.6899 %
Patience: 3/3

Early Stopping after 8 Epochen.
Imporovments totally: 4

totll running-tiems (s): 1070.52 Sekunden
totll running-tiems (min): 17.84 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.86 min	 | improvements: 1 Epochen	 | best_test_error: 19.9700 % 
last_layer: Gaussian	 epochs: 8 Epochen	| running_time: 17.84 min	 | improvements: 4 Epochen	 | best_test_error: 20.8302 % 

	 t: 2

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: Gaussian
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.5200 	 RMSE: 0.5902 
Diagonal-Error %: 41.7311 %

test_error:
MAE : 0.5393 	 RMSE: 0.6085 
Diagonal-Error %: 43.0255 %


	 Training: 



Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:09<00:00,  4.06s/it, loss=0.198]



train_error:
MAE : 0.2584 	 RMSE: 0.3252 
Diagonal-Error %: 22.9964 %

test_error:
MAE : 0.2868 	 RMSE: 0.3446 
Diagonal-Error %: 24.3666 %
Test-Diagonal-Error: 24.3666% | Improvment: 2

[15:25:09] Epoch 1: 233.47 Sekunden | Running_loss: 0.371 | test_diag_error=24.3666% | train_diag_error=22.9964% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:03<00:00,  3.85s/it, loss=0.214]



train_error:
MAE : 0.2073 	 RMSE: 0.2592 
Diagonal-Error %: 18.3302 %

test_error:
MAE : 0.2556 	 RMSE: 0.3041 
Diagonal-Error %: 21.5023 %
Test-Diagonal-Error: 21.5023% | Improvment: 3

[15:28:55] Epoch 2: 225.58 Sekunden | Running_loss: 0.227 | test_diag_error=21.5023% | train_diag_error=18.3302% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:03<00:00,  3.87s/it, loss=0.278]



train_error:
MAE : 0.1870 	 RMSE: 0.2364 
Diagonal-Error %: 16.7132 %

test_error:
MAE : 0.2493 	 RMSE: 0.2966 
Diagonal-Error %: 20.9760 %
Test-Diagonal-Error: 20.9760% | Improvment: 4

[15:32:47] Epoch 3: 232.57 Sekunden | Running_loss: 0.212 | test_diag_error=20.9760% | train_diag_error=16.7132% | 



Epoch 4: 100%|████████████████████████████████████████████████████████████████████████| 32/32 [02:03<00:00,  3.85s/it, loss=0.16]



train_error:
MAE : 0.1751 	 RMSE: 0.2293 
Diagonal-Error %: 16.2122 %

test_error:
MAE : 0.2792 	 RMSE: 0.3354 
Diagonal-Error %: 23.7165 %
Patience: 1/3

[15:36:36] Epoch 4: 228.89 Sekunden | Running_loss: 0.197 | test_diag_error=23.7165% | train_diag_error=16.2122% | 



Epoch 5: 100%|████████████████████████████████████████████████████████████████████████| 32/32 [02:07<00:00,  3.98s/it, loss=0.21]



train_error:
MAE : 0.1755 	 RMSE: 0.2224 
Diagonal-Error %: 15.7259 %

test_error:
MAE : 0.2616 	 RMSE: 0.3117 
Diagonal-Error %: 22.0417 %
Patience: 2/3

[15:40:28] Epoch 5: 231.81 Sekunden | Running_loss: 0.182 | test_diag_error=22.0417% | train_diag_error=15.7259% | 



Epoch 6: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:00<00:00,  3.77s/it, loss=0.181]



train_error:
MAE : 0.1525 	 RMSE: 0.1991 
Diagonal-Error %: 14.0772 %

test_error:
MAE : 0.2665 	 RMSE: 0.3163 
Diagonal-Error %: 22.3638 %
Patience: 3/3

Early Stopping after 6 Epochen.
Imporovments totally: 4

totll running-tiems (s): 1466.39 Sekunden
totll running-tiems (min): 24.44 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.86 min	 | improvements: 1 Epochen	 | best_test_error: 19.9700 % 
last_layer: Gaussian	 epochs: 6 Epochen	| running_time: 24.44 min	 | improvements: 4 Epochen	 | best_test_error: 20.9760 % 

	 t: 3

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: Gaussian
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.5160 	 RMSE: 0.5866 
Diagonal-Error %: 41.4807 %

test_error:
MAE : 0.5347 	 RMSE: 0.6044 
Diagonal-Error %: 42.7347 %


	 Training: 



Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:20<00:00,  4.40s/it, loss=0.231]



train_error:
MAE : 0.2272 	 RMSE: 0.2845 
Diagonal-Error %: 20.1164 %

test_error:
MAE : 0.2844 	 RMSE: 0.3382 
Diagonal-Error %: 23.9116 %
Test-Diagonal-Error: 23.9116% | Improvment: 2

[15:49:51] Epoch 1: 243.09 Sekunden | Running_loss: 0.328 | test_diag_error=23.9116% | train_diag_error=20.1164% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:08<00:00,  4.03s/it, loss=0.209]



train_error:
MAE : 0.2035 	 RMSE: 0.2545 
Diagonal-Error %: 17.9953 %

test_error:
MAE : 0.2699 	 RMSE: 0.3201 
Diagonal-Error %: 22.6372 %
Test-Diagonal-Error: 22.6372% | Improvment: 3

[15:53:51] Epoch 2: 240.07 Sekunden | Running_loss: 0.228 | test_diag_error=22.6372% | train_diag_error=17.9953% | 



Epoch 3: 100%|████████████████████████████████████████████████████████████████████████| 32/32 [02:16<00:00,  4.26s/it, loss=0.15]



train_error:
MAE : 0.1850 	 RMSE: 0.2356 
Diagonal-Error %: 16.6564 %

test_error:
MAE : 0.2645 	 RMSE: 0.3148 
Diagonal-Error %: 22.2568 %
Test-Diagonal-Error: 22.2568% | Improvment: 4

[15:58:00] Epoch 3: 249.19 Sekunden | Running_loss: 0.209 | test_diag_error=22.2568% | train_diag_error=16.6564% | 



Epoch 4: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:17<00:00,  4.30s/it, loss=0.175]



train_error:
MAE : 0.1709 	 RMSE: 0.2217 
Diagonal-Error %: 15.6800 %

test_error:
MAE : 0.2636 	 RMSE: 0.3151 
Diagonal-Error %: 22.2783 %
Patience: 1/3

[16:02:11] Epoch 4: 251.14 Sekunden | Running_loss: 0.200 | test_diag_error=22.2783% | train_diag_error=15.6800% | 



Epoch 5: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:18<00:00,  4.32s/it, loss=0.194]



train_error:
MAE : 0.1602 	 RMSE: 0.2095 
Diagonal-Error %: 14.8150 %

test_error:
MAE : 0.2901 	 RMSE: 0.3532 
Diagonal-Error %: 24.9738 %
Patience: 2/3

[16:06:21] Epoch 5: 250.06 Sekunden | Running_loss: 0.181 | test_diag_error=24.9738% | train_diag_error=14.8150% | 



Epoch 6: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:18<00:00,  4.32s/it, loss=0.183]



train_error:
MAE : 0.1511 	 RMSE: 0.1998 
Diagonal-Error %: 14.1258 %

test_error:
MAE : 0.2666 	 RMSE: 0.3179 
Diagonal-Error %: 22.4759 %
Patience: 3/3

Early Stopping after 6 Epochen.
Imporovments totally: 4

totll running-tiems (s): 1586.91 Sekunden
totll running-tiems (min): 26.45 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.86 min	 | improvements: 1 Epochen	 | best_test_error: 19.9700 % 
last_layer: Gaussian	 epochs: 6 Epochen	| running_time: 26.45 min	 | improvements: 4 Epochen	 | best_test_error: 22.2568 % 

	 t: 4

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: Gaussian
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.5197 	 RMSE: 0.5899 
Diagonal-Error %: 41.7156 %

test_error:
MAE : 0.5393 	 RMSE: 0.6085 
Diagonal-Error %: 43.0267 %


	 Training: 



Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:15<00:00,  4.23s/it, loss=0.296]



train_error:
MAE : 0.2797 	 RMSE: 0.3423 
Diagonal-Error %: 24.2032 %

test_error:
MAE : 0.3322 	 RMSE: 0.3972 
Diagonal-Error %: 28.0835 %
Test-Diagonal-Error: 28.0835% | Improvment: 2

[16:16:33] Epoch 1: 243.69 Sekunden | Running_loss: 0.389 | test_diag_error=28.0835% | train_diag_error=24.2032% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:10<00:00,  4.08s/it, loss=0.292]



train_error:
MAE : 0.2146 	 RMSE: 0.2698 
Diagonal-Error %: 19.0776 %

test_error:
MAE : 0.2812 	 RMSE: 0.3352 
Diagonal-Error %: 23.7049 %
Test-Diagonal-Error: 23.7049% | Improvment: 3

[16:20:23] Epoch 2: 230.13 Sekunden | Running_loss: 0.239 | test_diag_error=23.7049% | train_diag_error=19.0776% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:10<00:00,  4.07s/it, loss=0.211]



train_error:
MAE : 0.1995 	 RMSE: 0.2501 
Diagonal-Error %: 17.6816 %

test_error:
MAE : 0.2651 	 RMSE: 0.3137 
Diagonal-Error %: 22.1837 %
Test-Diagonal-Error: 22.1837% | Improvment: 4

[16:24:23] Epoch 3: 239.40 Sekunden | Running_loss: 0.218 | test_diag_error=22.1837% | train_diag_error=17.6816% | 



Epoch 4: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:12<00:00,  4.13s/it, loss=0.254]



train_error:
MAE : 0.1971 	 RMSE: 0.2436 
Diagonal-Error %: 17.2230 %

test_error:
MAE : 0.2727 	 RMSE: 0.3215 
Diagonal-Error %: 22.7321 %
Patience: 1/3

[16:28:26] Epoch 4: 243.09 Sekunden | Running_loss: 0.205 | test_diag_error=22.7321% | train_diag_error=17.2230% | 



Epoch 5: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:02<00:00,  3.83s/it, loss=0.203]



train_error:
MAE : 0.1645 	 RMSE: 0.2146 
Diagonal-Error %: 15.1739 %

test_error:
MAE : 0.2797 	 RMSE: 0.3304 
Diagonal-Error %: 23.3651 %
Patience: 2/3

[16:32:08] Epoch 5: 221.83 Sekunden | Running_loss: 0.195 | test_diag_error=23.3651% | train_diag_error=15.1739% | 



Epoch 6: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:57<00:00,  3.67s/it, loss=0.225]



train_error:
MAE : 0.1578 	 RMSE: 0.2121 
Diagonal-Error %: 14.9963 %

test_error:
MAE : 0.2831 	 RMSE: 0.3340 
Diagonal-Error %: 23.6177 %
Patience: 3/3

Early Stopping after 6 Epochen.
Imporovments totally: 4

totll running-tiems (s): 1509.22 Sekunden
totll running-tiems (min): 25.15 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.86 min	 | improvements: 1 Epochen	 | best_test_error: 19.9700 % 
last_layer: Gaussian	 epochs: 6 Epochen	| running_time: 25.15 min	 | improvements: 4 Epochen	 | best_test_error: 22.1837 % 

	 t: 5

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: Gaussian
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.5172 	 RMSE: 0.5877 
Diagonal-Error %: 41.5543 %

test_error:
MAE : 0.5366 	 RMSE: 0.6061 
Diagonal-Error %: 42.8550 %


	 Training: 



Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:19<00:00,  4.36s/it, loss=0.257]



train_error:
MAE : 0.2266 	 RMSE: 0.2780 
Diagonal-Error %: 19.6576 %

test_error:
MAE : 0.2789 	 RMSE: 0.3307 
Diagonal-Error %: 23.3847 %
Test-Diagonal-Error: 23.3847% | Improvment: 2

[16:41:52] Epoch 1: 252.06 Sekunden | Running_loss: 0.362 | test_diag_error=23.3847% | train_diag_error=19.6576% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:17<00:00,  4.30s/it, loss=0.309]



train_error:
MAE : 0.2076 	 RMSE: 0.2617 
Diagonal-Error %: 18.5018 %

test_error:
MAE : 0.2570 	 RMSE: 0.3047 
Diagonal-Error %: 21.5474 %
Test-Diagonal-Error: 21.5474% | Improvment: 3

[16:46:07] Epoch 2: 254.96 Sekunden | Running_loss: 0.227 | test_diag_error=21.5474% | train_diag_error=18.5018% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [02:14<00:00,  4.20s/it, loss=0.246]



train_error:
MAE : 0.1891 	 RMSE: 0.2441 
Diagonal-Error %: 17.2608 %

test_error:
MAE : 0.2835 	 RMSE: 0.3379 
Diagonal-Error %: 23.8943 %
Patience: 1/3

[16:49:26] Epoch 3: 198.25 Sekunden | Running_loss: 0.212 | test_diag_error=23.8943% | train_diag_error=17.2608% | 



Epoch 4: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:14<00:00,  2.34s/it, loss=0.207]



train_error:
MAE : 0.1824 	 RMSE: 0.2350 
Diagonal-Error %: 16.6177 %

test_error:
MAE : 0.2645 	 RMSE: 0.3144 
Diagonal-Error %: 22.2331 %
Patience: 2/3

[16:51:42] Epoch 4: 136.48 Sekunden | Running_loss: 0.203 | test_diag_error=22.2331% | train_diag_error=16.6177% | 



Epoch 5: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:20<00:00,  2.51s/it, loss=0.243]



train_error:
MAE : 0.1719 	 RMSE: 0.2290 
Diagonal-Error %: 16.1903 %

test_error:
MAE : 0.2645 	 RMSE: 0.3165 
Diagonal-Error %: 22.3777 %
Patience: 3/3

Early Stopping after 5 Epochen.
Imporovments totally: 3

totll running-tiems (s): 1100.67 Sekunden
totll running-tiems (min): 18.34 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.86 min	 | improvements: 1 Epochen	 | best_test_error: 19.9700 % 
last_layer: Gaussian	 epochs: 5 Epochen	| running_time: 18.34 min	 | improvements: 3 Epochen	 | best_test_error: 21.5474 % 

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=


 Parameter:
 best_test_error: [20.00081 20.06476 20.31059 20.2817  19.97003 20.83019 20.97602 22.25679
 22.18371 21.54738], 
 running_time: [ 7.59391784  7.00269289  7.46341295  8.6842122   7.86201617 17.84200476
 24.4397736  26.44851853 25.15366022 18.34444433] 


	 t: 1

  =#==#==#==#==#==#==#==

Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:15<00:00,  2.37s/it, loss=0.417]



train_error:
MAE : 0.3536 	 RMSE: 0.4392 
Diagonal-Error %: 31.0566 %

test_error:
MAE : 0.3602 	 RMSE: 0.4367 
Diagonal-Error %: 30.8811 %
Test-Diagonal-Error: 30.8811% | Improvment: 2

[16:57:28] Epoch 1: 140.46 Sekunden | Running_loss: 0.373 | test_diag_error=30.8811% | train_diag_error=31.0566% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:19<00:00,  2.48s/it, loss=0.283]



train_error:
MAE : 0.3396 	 RMSE: 0.4273 
Diagonal-Error %: 30.2154 %

test_error:
MAE : 0.3676 	 RMSE: 0.4413 
Diagonal-Error %: 31.2069 %
Patience: 1/3

[16:59:48] Epoch 2: 139.98 Sekunden | Running_loss: 0.351 | test_diag_error=31.2069% | train_diag_error=30.2154% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:14<00:00,  2.32s/it, loss=0.384]



train_error:
MAE : 0.3378 	 RMSE: 0.4297 
Diagonal-Error %: 30.3810 %

test_error:
MAE : 0.3824 	 RMSE: 0.4526 
Diagonal-Error %: 32.0008 %
Patience: 2/3

[17:02:13] Epoch 3: 144.60 Sekunden | Running_loss: 0.343 | test_diag_error=32.0008% | train_diag_error=30.3810% | 



Epoch 4: 100%|████████████████████████████████████████████████████████████████████████| 32/32 [01:25<00:00,  2.67s/it, loss=0.34]



train_error:
MAE : 0.3285 	 RMSE: 0.4240 
Diagonal-Error %: 29.9825 %

test_error:
MAE : 0.3723 	 RMSE: 0.4447 
Diagonal-Error %: 31.4436 %
Patience: 3/3

Early Stopping after 4 Epochen.
Imporovments totally: 2

totll running-tiems (s): 650.64 Sekunden
totll running-tiems (min): 10.84 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.86 min	 | improvements: 1 Epochen	 | best_test_error: 19.9700 % 
last_layer: Gaussian	 epochs: 5 Epochen	| running_time: 18.34 min	 | improvements: 3 Epochen	 | best_test_error: 21.5474 % 
last_layer: ReLU	 epochs: 4 Epochen	| running_time: 10.84 min	 | improvements: 2 Epochen	 | best_test_error: 30.8811 % 

	 t: 2

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: ReLU
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.4799 	 RMSE: 0.5552 
Diagonal-Error %: 39.2587 %

test_error:
MAE : 0.4606 	 RMSE: 0.5399 
Diagonal-Error %: 38.1758 %


	 Trai

Epoch 1: 100%|█████████████████████████████████████████████████████████████████████████| 32/32 [01:30<00:00,  2.84s/it, loss=0.2]



train_error:
MAE : 0.2321 	 RMSE: 0.2885 
Diagonal-Error %: 20.4012 %

test_error:
MAE : 0.2426 	 RMSE: 0.2900 
Diagonal-Error %: 20.5094 %
Test-Diagonal-Error: 20.5094% | Improvment: 2

[17:08:58] Epoch 1: 162.05 Sekunden | Running_loss: 0.293 | test_diag_error=20.5094% | train_diag_error=20.4012% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:29<00:00,  2.80s/it, loss=0.197]



train_error:
MAE : 0.1989 	 RMSE: 0.2507 
Diagonal-Error %: 17.7240 %

test_error:
MAE : 0.2441 	 RMSE: 0.2888 
Diagonal-Error %: 20.4229 %
Test-Diagonal-Error: 20.4229% | Improvment: 3

[17:11:46] Epoch 2: 167.92 Sekunden | Running_loss: 0.222 | test_diag_error=20.4229% | train_diag_error=17.7240% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:30<00:00,  2.83s/it, loss=0.168]



train_error:
MAE : 0.2080 	 RMSE: 0.2657 
Diagonal-Error %: 18.7909 %

test_error:
MAE : 0.2410 	 RMSE: 0.2862 
Diagonal-Error %: 20.2406 %
Test-Diagonal-Error: 20.2406% | Improvment: 4

[17:14:29] Epoch 3: 163.38 Sekunden | Running_loss: 0.200 | test_diag_error=20.2406% | train_diag_error=18.7909% | 



Epoch 4: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:33<00:00,  2.93s/it, loss=0.139]



train_error:
MAE : 0.1769 	 RMSE: 0.2316 
Diagonal-Error %: 16.3777 %

test_error:
MAE : 0.2606 	 RMSE: 0.3097 
Diagonal-Error %: 21.8994 %
Patience: 1/3

[17:17:18] Epoch 4: 168.74 Sekunden | Running_loss: 0.187 | test_diag_error=21.8994% | train_diag_error=16.3777% | 



Epoch 5: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:22<00:00,  2.56s/it, loss=0.176]



train_error:
MAE : 0.1479 	 RMSE: 0.1915 
Diagonal-Error %: 13.5434 %

test_error:
MAE : 0.2606 	 RMSE: 0.3061 
Diagonal-Error %: 21.6448 %
Patience: 2/3

[17:19:55] Epoch 5: 156.78 Sekunden | Running_loss: 0.170 | test_diag_error=21.6448% | train_diag_error=13.5434% | 



Epoch 6: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:31<00:00,  2.84s/it, loss=0.193]



train_error:
MAE : 0.1388 	 RMSE: 0.1846 
Diagonal-Error %: 13.0530 %

test_error:
MAE : 0.2693 	 RMSE: 0.3207 
Diagonal-Error %: 22.6776 %
Patience: 3/3

Early Stopping after 6 Epochen.
Imporovments totally: 4

totll running-tiems (s): 1065.58 Sekunden
totll running-tiems (min): 17.76 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.86 min	 | improvements: 1 Epochen	 | best_test_error: 19.9700 % 
last_layer: Gaussian	 epochs: 5 Epochen	| running_time: 18.34 min	 | improvements: 3 Epochen	 | best_test_error: 21.5474 % 
last_layer: ReLU	 epochs: 6 Epochen	| running_time: 17.76 min	 | improvements: 4 Epochen	 | best_test_error: 20.2406 % 

	 t: 3

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: ReLU
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.4755 	 RMSE: 0.5519 
Diagonal-Error %: 39.0258 %

test_error:
MAE : 0.4603 	 RMSE: 0.5397 
Diagonal-Error %: 38.1644 %


	 Tra

Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:28<00:00,  2.77s/it, loss=0.223]



train_error:
MAE : 0.2237 	 RMSE: 0.2751 
Diagonal-Error %: 19.4531 %

test_error:
MAE : 0.2407 	 RMSE: 0.2878 
Diagonal-Error %: 20.3518 %
Test-Diagonal-Error: 20.3518% | Improvment: 2

[17:26:41] Epoch 1: 164.54 Sekunden | Running_loss: 0.320 | test_diag_error=20.3518% | train_diag_error=19.4531% | 



Epoch 2: 100%|████████████████████████████████████████████████████████████████████████| 32/32 [01:26<00:00,  2.69s/it, loss=0.15]



train_error:
MAE : 0.2049 	 RMSE: 0.2537 
Diagonal-Error %: 17.9385 %

test_error:
MAE : 0.2445 	 RMSE: 0.2896 
Diagonal-Error %: 20.4806 %
Patience: 1/3

[17:29:19] Epoch 2: 158.64 Sekunden | Running_loss: 0.223 | test_diag_error=20.4806% | train_diag_error=17.9385% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:26<00:00,  2.71s/it, loss=0.202]



train_error:
MAE : 0.1844 	 RMSE: 0.2364 
Diagonal-Error %: 16.7183 %

test_error:
MAE : 0.2507 	 RMSE: 0.2971 
Diagonal-Error %: 21.0068 %
Patience: 2/3

[17:32:00] Epoch 3: 160.92 Sekunden | Running_loss: 0.210 | test_diag_error=21.0068% | train_diag_error=16.7183% | 



Epoch 4: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:23<00:00,  2.60s/it, loss=0.186]



train_error:
MAE : 0.1799 	 RMSE: 0.2315 
Diagonal-Error %: 16.3718 %

test_error:
MAE : 0.2588 	 RMSE: 0.3082 
Diagonal-Error %: 21.7928 %
Patience: 3/3

Early Stopping after 4 Epochen.
Imporovments totally: 2

totll running-tiems (s): 713.14 Sekunden
totll running-tiems (min): 11.89 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.86 min	 | improvements: 1 Epochen	 | best_test_error: 19.9700 % 
last_layer: Gaussian	 epochs: 5 Epochen	| running_time: 18.34 min	 | improvements: 3 Epochen	 | best_test_error: 21.5474 % 
last_layer: ReLU	 epochs: 4 Epochen	| running_time: 11.89 min	 | improvements: 2 Epochen	 | best_test_error: 20.3518 % 

	 t: 4

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: ReLU
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.4390 	 RMSE: 0.5194 
Diagonal-Error %: 36.7249 %

test_error:
MAE : 0.4229 	 RMSE: 0.5071 
Diagonal-Error %: 35.8545 %


	 Trai

Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:27<00:00,  2.74s/it, loss=0.349]



train_error:
MAE : 0.3550 	 RMSE: 0.4386 
Diagonal-Error %: 31.0167 %

test_error:
MAE : 0.3632 	 RMSE: 0.4392 
Diagonal-Error %: 31.0532 %
Test-Diagonal-Error: 31.0532% | Improvment: 2

[17:38:29] Epoch 1: 165.80 Sekunden | Running_loss: 0.376 | test_diag_error=31.0532% | train_diag_error=31.0167% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:31<00:00,  2.87s/it, loss=0.303]



train_error:
MAE : 0.3445 	 RMSE: 0.4312 
Diagonal-Error %: 30.4918 %

test_error:
MAE : 0.4086 	 RMSE: 0.4799 
Diagonal-Error %: 33.9335 %
Patience: 1/3

[17:41:25] Epoch 2: 175.88 Sekunden | Running_loss: 0.353 | test_diag_error=33.9335% | train_diag_error=30.4918% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:36<00:00,  3.01s/it, loss=0.275]



train_error:
MAE : 0.3370 	 RMSE: 0.4253 
Diagonal-Error %: 30.0742 %

test_error:
MAE : 0.3834 	 RMSE: 0.4549 
Diagonal-Error %: 32.1658 %
Patience: 2/3

[17:44:20] Epoch 3: 174.59 Sekunden | Running_loss: 0.342 | test_diag_error=32.1658% | train_diag_error=30.0742% | 



Epoch 4: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:42<00:00,  3.20s/it, loss=0.277]



train_error:
MAE : 0.3320 	 RMSE: 0.4249 
Diagonal-Error %: 30.0453 %

test_error:
MAE : 0.3746 	 RMSE: 0.4473 
Diagonal-Error %: 31.6305 %
Patience: 3/3

Early Stopping after 4 Epochen.
Imporovments totally: 2

totll running-tiems (s): 762.86 Sekunden
totll running-tiems (min): 12.71 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.86 min	 | improvements: 1 Epochen	 | best_test_error: 19.9700 % 
last_layer: Gaussian	 epochs: 5 Epochen	| running_time: 18.34 min	 | improvements: 3 Epochen	 | best_test_error: 21.5474 % 
last_layer: ReLU	 epochs: 4 Epochen	| running_time: 12.71 min	 | improvements: 2 Epochen	 | best_test_error: 31.0532 % 

	 t: 5

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
		 act: ReLU
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 Start: 

train_error:
MAE : 0.4799 	 RMSE: 0.5552 
Diagonal-Error %: 39.2557 %

test_error:
MAE : 0.4606 	 RMSE: 0.5400 
Diagonal-Error %: 38.1838 %


	 Trai

Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:38<00:00,  3.07s/it, loss=0.284]



train_error:
MAE : 0.2223 	 RMSE: 0.2752 
Diagonal-Error %: 19.4570 %

test_error:
MAE : 0.2502 	 RMSE: 0.3041 
Diagonal-Error %: 21.5006 %
Test-Diagonal-Error: 21.5006% | Improvment: 2

[17:51:29] Epoch 1: 170.74 Sekunden | Running_loss: 0.287 | test_diag_error=21.5006% | train_diag_error=19.4570% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:26<00:00,  2.69s/it, loss=0.182]



train_error:
MAE : 0.2006 	 RMSE: 0.2496 
Diagonal-Error %: 17.6511 %

test_error:
MAE : 0.2402 	 RMSE: 0.2871 
Diagonal-Error %: 20.3017 %
Test-Diagonal-Error: 20.3017% | Improvment: 3

[17:54:06] Epoch 2: 156.98 Sekunden | Running_loss: 0.222 | test_diag_error=20.3017% | train_diag_error=17.6511% | 



Epoch 3: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:29<00:00,  2.79s/it, loss=0.208]



train_error:
MAE : 0.1873 	 RMSE: 0.2389 
Diagonal-Error %: 16.8932 %

test_error:
MAE : 0.2431 	 RMSE: 0.2935 
Diagonal-Error %: 20.7509 %
Patience: 1/3

[17:56:45] Epoch 3: 159.62 Sekunden | Running_loss: 0.208 | test_diag_error=20.7509% | train_diag_error=16.8932% | 



Epoch 4: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:30<00:00,  2.81s/it, loss=0.214]



train_error:
MAE : 0.1637 	 RMSE: 0.2140 
Diagonal-Error %: 15.1310 %

test_error:
MAE : 0.2437 	 RMSE: 0.2912 
Diagonal-Error %: 20.5902 %
Patience: 2/3

[17:59:27] Epoch 4: 161.28 Sekunden | Running_loss: 0.187 | test_diag_error=20.5902% | train_diag_error=15.1310% | 



Epoch 5: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:33<00:00,  2.91s/it, loss=0.186]



train_error:
MAE : 0.1662 	 RMSE: 0.2161 
Diagonal-Error %: 15.2806 %

test_error:
MAE : 0.3030 	 RMSE: 0.3660 
Diagonal-Error %: 25.8803 %
Patience: 3/3

Early Stopping after 5 Epochen.
Imporovments totally: 3

totll running-tiems (s): 893.20 Sekunden
totll running-tiems (min): 14.89 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.86 min	 | improvements: 1 Epochen	 | best_test_error: 19.9700 % 
last_layer: Gaussian	 epochs: 5 Epochen	| running_time: 18.34 min	 | improvements: 3 Epochen	 | best_test_error: 21.5474 % 
last_layer: ReLU	 epochs: 5 Epochen	| running_time: 14.89 min	 | improvements: 3 Epochen	 | best_test_error: 20.3017 % 

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=


 Parameter:
 best_test_error: [20.00081 20.06476 20.31059 20.2817  19.97003 20.83019 20.97602 22.25679
 22.18371 21.54738 30.8811  20.24064 20.35178 31.05322 20.3017 ], 
 running_

Epoch 1: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:35<00:00,  2.97s/it, loss=0.167]



train_error:
MAE : 0.2175 	 RMSE: 0.2711 
Diagonal-Error %: 19.1664 %

test_error:
MAE : 0.2430 	 RMSE: 0.2887 
Diagonal-Error %: 20.4125 %
Test-Diagonal-Error: 20.4125% | Improvment: 2

[18:06:16] Epoch 1: 171.28 Sekunden | Running_loss: 0.260 | test_diag_error=20.4125% | train_diag_error=19.1664% | 



Epoch 2: 100%|███████████████████████████████████████████████████████████████████████| 32/32 [01:26<00:00,  2.72s/it, loss=0.164]



train_error:


	 dataset_name: 	 norm_labels.csv
	 def_dataset_size: train: 1000, 	 test: 200
	 batch_Size: 	 32
	 def_dataset: 	 norm_subject
	 learning_rate: 	 0.0001
	 epochs: 	 500
	 patience: 	 3
     Layer 4 : False
     FC : True

# Sigmoid :
last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.59 min	 | improvements: 1 Epochen	 | best_test_error: 20.0008 % 
last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.00 min	 | improvements: 1 Epochen	 | best_test_error: 20.0648 % 
last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.46 min	 | improvements: 1 Epochen	 | best_test_error: 20.3106 % 
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 8.68 min	 | improvements: 2 Epochen	 | best_test_error: 20.2817 %
last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.86 min	 | improvements: 1 Epochen	 | best_test_error: 19.9700 %

best_test_error1 = [20.00081, 20.06476, 20.31059, 20.2817, 19.97003]
run_time1 =        [7.594, 7.003, 7.463, 8.684, 7.862]


# Gaussien :
last_layer: Gaussian  epochs: 8 Epochen	| running_time: 17.84 min	 | improvements: 4 Epochen	 | best_test_error: 20.8302 %
last_layer: Gaussian  epochs: 6 Epochen	| running_time: 24.44 min	 | improvements: 4 Epochen	 | best_test_error: 20.9760 % 
last_layer: Gaussian  epochs: 6 Epochen	| running_time: 26.45 min	 | improvements: 4 Epochen	 | best_test_error: 22.2568 %
last_layer: Gaussian  epochs: 6 Epochen	| running_time: 25.15 min	 | improvements: 4 Epochen	 | best_test_error: 22.1837 %


best_test_error2 = []
run_time2 = []

# ReLU :

best_test_error3 = []
run_time3 = []

# None:

best_test_error4 = []
run_time4 = []

In [24]:

print(f"\n\t dataset_name: \t {dataset_name}")
print(f"\t def_dataset_size: train: {def_dataset_size[0]}, \t test: {def_dataset_size[1]}")
print(f"\t batch_Size: \t {batch_Size}")
print(f"\t def_dataset: \t {def_dataset}")
print(f"\t learning_rate: \t {learning_rate}")
print(f"\t epochs: \t {epochs}")
print(f"\t patience: \t {patience}")



parm1, parm2 = [], []

parm_test_error = []
parm_run_time = []



for t in range(5):
    
    print(f"\n\t t: {t + 1}")
    
    criterion = nn.L1Loss()
    
    criterion_base = nn.L1Loss()
    
    epochs = epochs
    
    if globals().get("bas_const_err") is None:
        bas_const_err = 27.245
    
    if globals().get("bas_rand_err") is None:
        bas_rand_err = 38.961
        
    
    # model_output = './models'
    # model_dir= Path(model_output)
    
    # if not os.path.exists(model_dir):
    #     model_dir.mkdir(
    #         parents=True,
    #         exist_ok=True
    #     )
    
    
    # diagrams_output = './results/diagrams'
    # diagrams_dir= Path(diagrams_output)
    
    # if not os.path.exists(diagrams_dir):
    #     diagrams_dir.mkdir(
    #         parents=True,
    #         exist_ok=True
    #     )
    
    diag_test_errors = {}
    diag_train_errors = {}
    
    
    act_time_epochs = {}
    
    
    diag_test_error, diag_train_error = [], []
    
    acts = ['Sigmoid', 'Gaussian', 'ReLU', 'None']
    
    act = acts[0]
    
    # for act in ['Sigmoid', 'Gaussian', 'ReLU', 'None']:
    # for act in ['Sigmoid']:
    # for act in ['None']:
    
    if act == 'Sigmoid':
    
    # if act == 'None':
    
        train_start = time.perf_counter()
      
        model, model_name = reset_model(act=act)
    
        active_func = act
    
        diag_test_errors[act] = []
        diag_train_errors[act] = []
    
        best_error = float("inf")
    
        t = 0                      # Number Epochen without Optimierung
        e = 0                      # Number Epochen with Optimierung
    
    
        model.to(device)
    
    
    
        for param in model.parameters():
            param.requires_grad = False
    
        # Unfreeze the head
        for param in model.layer4.parameters():
            param.requires_grad=False
            print(f"param in model.layer4.parameters: {param.requires_grad}")
    
        for param in model.fc.parameters():
            param.requires_grad=True
            print(f"param in model.fc.parameters: {param.requires_grad}")
    
    
        optimizer = torch.optim.AdamW(
            filter(lambda p:p.requires_grad, model.parameters()),
            lr=learning_rate,
            weight_decay=weight_Decay
        )
    
        print('\n ',"=#=" * 25)
        print(f"\t\t act: {act}")
        print(' ',"=#=" * 25)
    
        print("\n\t Start: \n")
        
        print("train_error:")
        train_mae, train_rmse, train_diag_pct = diagonal_errors(model, train_loader, device)
        diag_train_error.append(np.round(train_diag_pct, 4))
        
        diag_train_errors[act].append(np.round(train_diag_pct, 4))
    
    
    
        print("\ntest_error:")
        test_mae, test_rmse, test_diag_pct = diagonal_errors(model, test_loader, device)
        diag_test_error.append(np.round(test_diag_pct, 4))
    
        diag_test_errors[act].append(np.round(test_diag_pct, 4))

        if best_error is None or test_diag_pct < best_error:    
            # set the first test-error
            best_error = test_diag_pct
            t = 0
            e += 1
    
    
        print("\n\n\t Training: \n")
    
        for epoch in range(epochs):
    
            epoch_start = time.perf_counter()
    
            model.train()
            running_loss = 0
    
            loop = tqdm(
                train_loader,
                desc=f"Epoch {epoch + 1}"
            )
    
            for images, targets in loop:
                images = images.to(device)
                targets = targets.to(device)
                optimizer.zero_grad()
                preds = model(images)
    
                ################################
                
                # Loss 1:
                loss = criterion(
                    preds,
                    targets
                )
    
                
                # Loss 2: 
                # loss = sensitive_loss(
                #     preds,
                #     targets
                # )
                
                ################################
    
                loss.backward()
                optimizer.step()
                running_loss += loss.item()
    
                loop.set_postfix(
                    loss=loss.item()
                )
    
            # epoch_end = time.perf_counter()
    
            print(f"\ntrain_error:")
            train_mae, train_rmse, train_diag_pct = diagonal_errors(model, train_loader, device)
            diag_train_error.append(np.round(train_diag_pct, 4))
    
            diag_train_errors[act].append(np.round(train_diag_pct, 4))
    
            print(f"\ntest_error:")
            test_mae, test_rmse, test_diag_pct = diagonal_errors(model, test_loader, device)
            diag_test_error.append(np.round(test_diag_pct, 4))
    
            diag_test_errors[act].append(np.round(test_diag_pct, 4))
    
            # --------------------------------------------------
            # Early Stopping
            # --------------------------------------------------
            
            if best_error is None or test_diag_pct < best_error:
            
                # find an improvement
                best_error = test_diag_pct
                t = 0
                e += 1
            
                print(
                    f"Test-Diagonal-Error: {test_diag_pct:.4f}% | "
                    f"Improvment: {e}"
                )
            
                # save the better Modell
                # torch.save(
                #     model.state_dict(),
                #     f"./models/best_optim-model_"
                #     f"{def_dataset}_{def_dataset_size[0]}-{def_dataset_size[1]}.path"
                # )
    
                # torch.save(
                #     model.state_dict(),
                #     f"./models/best-model_"
                #     f"{model_name}_{act}.path"
                # )
            
            else:
            
                # without imporovement
                t += 1
            
                print(
                    f"Patience: {t}/{patience}"
                )
            
                if t >= patience:
                    print(
                        f"\nEarly Stopping after {epoch + 1} Epochen."
                    )
                    print(
                        f"Imporovments totally: {e}"
                    )
                    break
    
    
    
            epoch_end = time.perf_counter()
    
    
            print(
                f"\n[{datetime.now().strftime('%H:%M:%S')}] Epoch {epoch + 1}: {epoch_end - epoch_start:.2f} Sekunden | "
                f"Running_loss: {running_loss / len(train_loader):.3f} | "
                f"test_diag_error={test_diag_pct:.4f}% | "
                f"train_diag_error={train_diag_pct:.4f}% | \n"
            )
    
            # torch.save(model.state_dict(),
            #         f"./models/last_best_optim_model_{def_dataset}_{def_dataset_size[0]}-{def_dataset_size[1]}.path")
    
            # torch.save(
            #         model.state_dict(),
            #         f"./models/last-model_"
            #         f"{model_name}_{act}.path"
            #     )
    
    
        train_end = time.perf_counter()
    
    
        elapsed_running_time = train_end - train_start
        print(f"\ntotll running-tiems (s): {elapsed_running_time:.2f} Sekunden")
        print(f"totll running-tiems (min): {elapsed_running_time / 60:.2f} Minuten\n")
    
        
        # act_time[act].append(elapsed_running_time)
        # act_epoch[act].append(e)
    
        act_time_epochs[act] = {
            "time_minutes": elapsed_running_time / 60,
            "epochs": epoch + 1,
            "improvements": e,
            "best_test_error": best_error
        }
    
    
        parm1.append(best_error)
        parm2.append(elapsed_running_time / 60)

    
        # print(f"\n\nDiagonal_train_error: {np.float64(diag_train_error)}")
        # print(f"\n\nDiagonal_test_error: {np.float64(diag_test_error)}")

    for act, values in act_time_epochs.items():
        print(
            f"last_layer: {act}\t"
            f" epochs: {values['epochs']} Epochen\t|"
            f" running_time: {values['time_minutes']:.2f} min\t |"
            f" improvements: {values['improvements']} Epochen\t |"
            f" best_test_error: {values['best_test_error']:.4f} % "
        )
        # parm_test_error.append(float(f"{values['best_test_error']:.4f}"))
        # parm_run_time.append(float(f"{values['time_minutes']:.2f}"))

    print('\n ',"=#=" * 25)
    print(' ',"=#=" * 25)

# print(f"\n\n Parameter:\n best_test_error: {param_test_error}, \n running_time: {parm_run_time} \n")
print(f"\n\n Parameter:\n best_test_error: {np.float64(parm1)}, \n running_time: {np.float64(parm2)} \n")



	 dataset_name: 	 norm_labels.csv
	 def_dataset_size: train: 10000, 	 test: 2000
	 batch_Size: 	 32
	 def_dataset: 	 norm_subject
	 learning_rate: 	 0.0001
	 epochs: 	 500
	 patience: 	 3

	 t: 1
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.fc.parameters: True
param in model.fc.parameters: True
param in model.fc.parameters: True
param in model.fc.parameters: True
param in model.fc.parameters: True
param in model.fc.parameters

Epoch 1: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [08:31<00:00,  1.63s/it, loss=0.235]



train_error:
MAE : 0.2339 	 RMSE: 0.2745 
Diagonal-Error %: 19.4108 %

test_error:
MAE : 0.2345 	 RMSE: 0.2785 
Diagonal-Error %: 19.6916 %
Test-Diagonal-Error: 19.6916% | Improvment: 2

[19:40:33] Epoch 1: 1071.67 Sekunden | Running_loss: 0.235 | test_diag_error=19.6916% | train_diag_error=19.4108% | 



Epoch 2: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:50<00:00,  1.50s/it, loss=0.267]



train_error:
MAE : 0.2331 	 RMSE: 0.2736 
Diagonal-Error %: 19.3481 %

test_error:
MAE : 0.2348 	 RMSE: 0.2785 
Diagonal-Error %: 19.6917 %
Patience: 1/3

[19:57:25] Epoch 2: 1011.67 Sekunden | Running_loss: 0.234 | test_diag_error=19.6917% | train_diag_error=19.3481% | 



Epoch 3: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:48<00:00,  1.50s/it, loss=0.228]



train_error:
MAE : 0.2314 	 RMSE: 0.2724 
Diagonal-Error %: 19.2629 %

test_error:
MAE : 0.2363 	 RMSE: 0.2796 
Diagonal-Error %: 19.7723 %
Patience: 2/3

[20:13:59] Epoch 3: 993.84 Sekunden | Running_loss: 0.233 | test_diag_error=19.7723% | train_diag_error=19.2629% | 



Epoch 4: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:51<00:00,  1.51s/it, loss=0.227]



train_error:
MAE : 0.2300 	 RMSE: 0.2711 
Diagonal-Error %: 19.1678 %

test_error:
MAE : 0.2363 	 RMSE: 0.2802 
Diagonal-Error %: 19.8159 %
Patience: 3/3

Early Stopping after 4 Epochen.
Imporovments totally: 2

totll running-tiems (s): 4730.15 Sekunden
totll running-tiems (min): 78.84 Minuten

last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 78.84 min	 | improvements: 2 Epochen	 | best_test_error: 19.6916 % 

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 t: 2
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.

Epoch 1: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:52<00:00,  1.51s/it, loss=0.236]



train_error:
MAE : 0.2338 	 RMSE: 0.2742 
Diagonal-Error %: 19.3923 %

test_error:
MAE : 0.2344 	 RMSE: 0.2782 
Diagonal-Error %: 19.6736 %
Test-Diagonal-Error: 19.6736% | Improvment: 2

[20:56:10] Epoch 1: 1006.31 Sekunden | Running_loss: 0.235 | test_diag_error=19.6736% | train_diag_error=19.3923% | 



Epoch 2: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:55<00:00,  1.52s/it, loss=0.227]



train_error:
MAE : 0.2323 	 RMSE: 0.2732 
Diagonal-Error %: 19.3177 %

test_error:
MAE : 0.2349 	 RMSE: 0.2790 
Diagonal-Error %: 19.7280 %
Patience: 1/3

[21:13:00] Epoch 2: 1010.13 Sekunden | Running_loss: 0.234 | test_diag_error=19.7280% | train_diag_error=19.3177% | 



Epoch 3: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:50<00:00,  1.50s/it, loss=0.248]



train_error:
MAE : 0.2314 	 RMSE: 0.2725 
Diagonal-Error %: 19.2665 %

test_error:
MAE : 0.2361 	 RMSE: 0.2795 
Diagonal-Error %: 19.7668 %
Patience: 2/3

[21:29:45] Epoch 3: 1004.15 Sekunden | Running_loss: 0.233 | test_diag_error=19.7668% | train_diag_error=19.2665% | 



Epoch 4: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [08:00<00:00,  1.53s/it, loss=0.267]



train_error:
MAE : 0.2307 	 RMSE: 0.2718 
Diagonal-Error %: 19.2212 %

test_error:
MAE : 0.2370 	 RMSE: 0.2801 
Diagonal-Error %: 19.8075 %
Patience: 3/3

Early Stopping after 4 Epochen.
Imporovments totally: 2

totll running-tiems (s): 4560.08 Sekunden
totll running-tiems (min): 76.00 Minuten

last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 76.00 min	 | improvements: 2 Epochen	 | best_test_error: 19.6736 % 

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 t: 3
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.

Epoch 1: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:51<00:00,  1.51s/it, loss=0.279]



train_error:
MAE : 0.2343 	 RMSE: 0.2746 
Diagonal-Error %: 19.4176 %

test_error:
MAE : 0.2351 	 RMSE: 0.2791 
Diagonal-Error %: 19.7342 %
Patience: 1/3

[22:12:10] Epoch 1: 1007.14 Sekunden | Running_loss: 0.235 | test_diag_error=19.7342% | train_diag_error=19.4176% | 



Epoch 2: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:47<00:00,  1.49s/it, loss=0.247]



train_error:
MAE : 0.2333 	 RMSE: 0.2736 
Diagonal-Error %: 19.3448 %

test_error:
MAE : 0.2364 	 RMSE: 0.2795 
Diagonal-Error %: 19.7656 %
Patience: 2/3

[22:28:48] Epoch 2: 997.88 Sekunden | Running_loss: 0.234 | test_diag_error=19.7656% | train_diag_error=19.3448% | 



Epoch 3: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [08:26<00:00,  1.62s/it, loss=0.197]



train_error:
MAE : 0.2329 	 RMSE: 0.2741 
Diagonal-Error %: 19.3788 %

test_error:
MAE : 0.2385 	 RMSE: 0.2819 
Diagonal-Error %: 19.9300 %
Patience: 3/3

Early Stopping after 3 Epochen.
Imporovments totally: 1

totll running-tiems (s): 3577.52 Sekunden
totll running-tiems (min): 59.63 Minuten

last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 59.63 min	 | improvements: 1 Epochen	 | best_test_error: 19.6978 % 

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 t: 4
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.

Epoch 1: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:38<00:00,  1.46s/it, loss=0.257]



train_error:
MAE : 0.2342 	 RMSE: 0.2747 
Diagonal-Error %: 19.4219 %

test_error:
MAE : 0.2347 	 RMSE: 0.2785 
Diagonal-Error %: 19.6930 %
Test-Diagonal-Error: 19.6930% | Improvment: 2

[23:13:02] Epoch 1: 976.91 Sekunden | Running_loss: 0.235 | test_diag_error=19.6930% | train_diag_error=19.4219% | 



Epoch 2: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:38<00:00,  1.47s/it, loss=0.243]



train_error:
MAE : 0.2328 	 RMSE: 0.2733 
Diagonal-Error %: 19.3242 %

test_error:
MAE : 0.2348 	 RMSE: 0.2787 
Diagonal-Error %: 19.7040 %
Patience: 1/3

[23:29:20] Epoch 2: 977.70 Sekunden | Running_loss: 0.234 | test_diag_error=19.7040% | train_diag_error=19.3242% | 



Epoch 3: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:37<00:00,  1.46s/it, loss=0.208]



train_error:
MAE : 0.2321 	 RMSE: 0.2734 
Diagonal-Error %: 19.3300 %

test_error:
MAE : 0.2362 	 RMSE: 0.2803 
Diagonal-Error %: 19.8216 %
Patience: 2/3

[23:45:45] Epoch 3: 984.67 Sekunden | Running_loss: 0.233 | test_diag_error=19.8216% | train_diag_error=19.3300% | 



Epoch 4: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:49<00:00,  1.50s/it, loss=0.251]



train_error:
MAE : 0.2297 	 RMSE: 0.2713 
Diagonal-Error %: 19.1837 %

test_error:
MAE : 0.2377 	 RMSE: 0.2813 
Diagonal-Error %: 19.8891 %
Patience: 3/3

Early Stopping after 4 Epochen.
Imporovments totally: 2

totll running-tiems (s): 4579.73 Sekunden
totll running-tiems (min): 76.33 Minuten

last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 76.33 min	 | improvements: 2 Epochen	 | best_test_error: 19.6930 % 

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=

	 t: 5
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.layer4.parameters: False
param in model.

Epoch 1: 100%|██████████████████████████████████████████████████████████████████████| 313/313 [07:44<00:00,  1.49s/it, loss=0.26]



train_error:
MAE : 0.2341 	 RMSE: 0.2747 
Diagonal-Error %: 19.4226 %

test_error:
MAE : 0.2341 	 RMSE: 0.2780 
Diagonal-Error %: 19.6562 %
Test-Diagonal-Error: 19.6562% | Improvment: 2

[00:27:46] Epoch 1: 984.90 Sekunden | Running_loss: 0.235 | test_diag_error=19.6562% | train_diag_error=19.4226% | 



Epoch 2: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:38<00:00,  1.46s/it, loss=0.207]



train_error:
MAE : 0.2337 	 RMSE: 0.2741 
Diagonal-Error %: 19.3844 %

test_error:
MAE : 0.2345 	 RMSE: 0.2787 
Diagonal-Error %: 19.7062 %
Patience: 1/3

[00:44:04] Epoch 2: 978.02 Sekunden | Running_loss: 0.234 | test_diag_error=19.7062% | train_diag_error=19.3844% | 



Epoch 3: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:36<00:00,  1.46s/it, loss=0.213]



train_error:
MAE : 0.2319 	 RMSE: 0.2725 
Diagonal-Error %: 19.2673 %

test_error:
MAE : 0.2349 	 RMSE: 0.2784 
Diagonal-Error %: 19.6882 %
Patience: 2/3

[01:00:20] Epoch 3: 975.94 Sekunden | Running_loss: 0.234 | test_diag_error=19.6882% | train_diag_error=19.2673% | 



Epoch 4: 100%|█████████████████████████████████████████████████████████████████████| 313/313 [07:37<00:00,  1.46s/it, loss=0.228]



train_error:
MAE : 0.2301 	 RMSE: 0.2719 
Diagonal-Error %: 19.2241 %

test_error:
MAE : 0.2356 	 RMSE: 0.2794 
Diagonal-Error %: 19.7576 %
Patience: 3/3

Early Stopping after 4 Epochen.
Imporovments totally: 2

totll running-tiems (s): 4448.34 Sekunden
totll running-tiems (min): 74.14 Minuten

last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 74.14 min	 | improvements: 2 Epochen	 | best_test_error: 19.6562 % 

  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=
  =#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#=


 Parameter:
 best_test_error: [19.69159 19.67359 19.69785 19.69303 19.65619], 
 running_time: [78.83583934 76.00137809 59.62526972 76.32883505 74.13899965] 



	 dataset_name: 	 norm_labels.csv
	 def_dataset_size: train: 10000, 	 test: 2000
	 batch_Size: 	 32
	 def_dataset: 	 norm_subject
	 learning_rate: 	 0.0001
	 epochs: 	 500
	 patience: 	 3

     param in model.layer4.parameters: False
     param in model.fc.parameters: True

# def_dataset_size: train: 10000, 	 test: 2000
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 78.84 min	 | improvements: 2 Epochen	 | best_test_error: 19.6916 % 
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 76.00 min	 | improvements: 2 Epochen	 | best_test_error: 19.6736 %
last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 59.63 min	 | improvements: 1 Epochen	 | best_test_error: 19.6978 % 
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 76.33 min	 | improvements: 2 Epochen	 | best_test_error: 19.6930 % 
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 74.14 min	 | improvements: 2 Epochen	 | best_test_error: 19.6562 %

best_test_error =  [19.69159, 19.67359, 19.69785, 19.69303, 19.65619] 
running_time    =  [78.84, 76.00, 59.63, 76.33, 74.14] 


	 dataset_name: 	 norm_labels.csv
	 def_dataset_size: train: 1000, 	 test: 200
	 batch_Size: 	 32
	 def_dataset: 	 norm_subject
	 learning_rate: 	 0.0001
	 epochs: 	 500
	 patience: 	 3
     
     param in model.layer4.parameters: False
     param in model.fc.parameters: True
     
# def_dataset_size: train: 1000, 	 test: 200
last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.06 min	 | improvements: 1 Epochen	 | best_test_error: 20.0895 % 
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 7.91 min	 | improvements: 2 Epochen	 | best_test_error: 20.0419 %
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 7.48 min	 | improvements: 2 Epochen	 | best_test_error: 20.0626 % 
last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 5.75 min	 | improvements: 1 Epochen	 | best_test_error: 20.1050 %
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 7.63 min	 | improvements: 2 Epochen	 | best_test_error: 20.0442 % 



best_test_error = [20.08953, 20.04193, 20.06257, 20.10499, 20.04419]
running_time    = [7.06, 7.91, 7.48, 5.75, 7.63]



In [ ]:
# dataset_size: 1000 & 200
best_test_error = [20.08953, 20.04193, 20.06257, 20.10499, 20.04419]
running_time    = [7.06, 7.91, 7.48, 5.75, 7.63]

# dataset_size: 10000 & 2000
best_test_error =  [19.69159, 19.67359, 19.69785, 19.69303, 19.65619] 
running_time    =  [78.84, 76.00, 59.63, 76.33, 74.14] 

In [ ]:
# FC + lay 4:
best_test_error =  [19.95091, 20.2972, 20.07323, 20.04155, 20.19138]
running_time    =  [7.626, 10.104, 7.248, 7.389, 7.081]

# FC only:
best_test_error = [20.08953, 20.04193, 20.06257, 20.10499, 20.04419], 
running_time    = [7.057, 7.908 7.478, 5.753, 7.628]

In [49]:

test_error_parm, run_time_parm = [], []
for i in range(len(parameter)):
    if i % 2 == 0:
        test_error_parm.append((np.round(parameter[i], 5)))
    else:
        run_time_parm.append(np.round(parameter[i], 3))

print(f"\n test_error_parm: {np.float64(test_error_parm)} \n run_time_parm: {np.float64(run_time_parm)}\n\n")


parameter2 = []

parm_test_error = []
parm_run_time = []

for act, values in act_time_epochs.items():
    print(
        f"last_layer: {act}\t"
        f" epochs: {values['epochs']} Epochen\t|"
        f" running_time: {values['time_minutes']:.2f} min\t |"
        f" improvements: {values['improvements']} Epochen\t |"
        f" best_test_error: {values['best_test_error']:.4f} % "
    )
    parameter2.append(float(f"{values['best_test_error']:.4f}"))
    parm_test_error.append(float(f"{values['best_test_error']:.4f}"))
    parm_run_time.append(float(f"{values['time_minutes']:.2f}"))

print(f"\n parameter2: {parameter2}")
print(f"\n parameter: {np.float64([np.float64(parameter[p]) for p in range(len(parameter))])}")
print(f"\n run_time: {parm_run_time}")
print(f"\n test_error: {parm_test_error}")


 test_error_parm: [20.19735 20.17375 19.98697 20.11189 20.06467] 
 run_time_parm: [10.507 11.879  6.817 11.947  6.362]


last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 6.36 min	 | improvements: 1 Epochen	 | best_test_error: 20.0647 % 

 parameter2: [20.0647]

 parameter: [20.19735    10.50747222 20.17375    11.87886853 19.98697     6.81678813
 20.11189    11.94715597 20.06467     6.36239556]

 run_time: [6.36]

 test_error: [20.0647]


    dataset_name: 	  norm_labels.csv
    def_dataset_size: train: 1000, 	 test: 200
    batch_Size: 	  128
    dataset-splits:   norm_subject
    learning_rate: 	  0.0001
    epochs: 	      500
    patience: 	      3

## batch_size(32 vs. 64 vs. 132):
 * dataset_name: 	   norm_labels.csv
 * dataset_size:       train: 1000, 	 test: 200
 * dataset-splits: 	   norm_subject
 * batch_Size: 	       32 vs. 64 vs. 132      <============
 * learning_rate: 	   1e-4

	 dataset_name: 	 norm_labels.csv
	 def_dataset_size: train: 1000, 	 test: 200
	 batch_Size: 	 32
	 def_dataset: 	 norm_subject
	 learning_rate: 	 1e-05
	 epochs: 	 500
	 patience: 	 3

# batch_size: 	 32
 
* ** try 1 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 7.44 min	 | improvements: 2 Epochen	 | best_test_error: 20.0913 % 

* ** try 2 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 7.34 min	 | improvements: 2 Epochen	 | best_test_error: 20.0092 %  

* ** try 3 **:
last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 6.07 min	 | improvements: 1 Epochen	 | best_test_error: 20.0785 %

* ** try 4 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 8.69 min	 | improvements: 2 Epochen	 | best_test_error: 20.0367 % 

* ** try 5 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 8.65 min	 | improvements: 2 Epochen	 | best_test_error: 20.0945 %

########################################################################
	 dataset_name: 	 norm_labels.csv
	 def_dataset_size: train: 1000, 	 test: 200
	 batch_Size: 	 64
	 def_dataset: 	 norm_subject
	 learning_rate: 	 1e-05
	 epochs: 	 500
	 patience: 	 3

# batch_size: 	 64

* ** try 1 **:
last_layer: Sigmoid	 epochs: 5 Epochen	| running_time: 10.26 min	 | improvements: 3 Epochen	 | best_test_error: 20.2225 % 

* ** try 2 **:
last_layer: Sigmoid	 epochs: 7 Epochen	| running_time: 14.27 min	 | improvements: 5 Epochen	 | best_test_error: 20.2962 %

* ** try 3 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 8.27 min	 | improvements: 2 Epochen	 | best_test_error: 20.1555 %

* ** try 4 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 8.08 min	 | improvements: 2 Epochen	 | best_test_error: 19.9577 %

* ** try 5 **:
last_layer: Sigmoid	 epochs: 5 Epochen	| running_time: 10.08 min	 | improvements: 3 Epochen	 | best_test_error: 19.9995 %

########################################################################
	 dataset_name: 	 norm_labels.csv
	 def_dataset_size: train: 1000, 	 test: 200
	 batch_Size: 	 128
	 def_dataset: 	 norm_subject
	 learning_rate: 	 1e-05
	 epochs: 	 500
	 patience: 	 3

# batch_size: 	 128
 
* ** try 1 **:
last_layer: Sigmoid	 epochs: 5 Epochen	| running_time: 10.51 min	 | improvements: 3 Epochen	 | best_test_error: 20.1974 %

* ** try 2 **:
last_layer: Sigmoid	 epochs: 6 Epochen	| running_time: 11.88 min	 | improvements: 4 Epochen	 | best_test_error: 20.1737 % 

* ** try 3 **:
last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 6.82 min	 | improvements: 1 Epochen	 | best_test_error: 19.9870 %

* ** try 4 **:
last_layer: Sigmoid	 epochs: 6 Epochen	| running_time: 11.95 min	 | improvements: 4 Epochen	 | best_test_error: 20.1119 %

* ** try 5 **:
last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 6.36 min	 | improvements: 1 Epochen	 | best_test_error: 20.0647 %


In [51]:
parm_bat32_te = [20.0913, 20.0092, 20.0785, 20.0367, 20.0945]
parm_bat32_rt = [7.44, 7.34, 6.07, 8.69, 8.65]

parm_bat64_te = [20.2225, 20.2962, 20.1555, 19.9577, 19.9995]
parm_bat64_rt = [10.26, 14.27, 8.27, 8.08, 10.08]

parm_bat128_te = [20.19735, 20.17375, 19.98697, 20.11189, 20.06467]
parm_bat128_rt = [10.507, 11.879, 6.817, 11.947, 6.362]


In [59]:
# parm_bat_32: 

# parm_bat32_te = [20.0913, 20.0092, 20.0785, 20.0367, 20.0945]
# parm_bat32_rt = [7.44, 7.34, 6.07, 8.69, 8.65]

parm_test_error   = parm_bat32_te
parm_running_time = parm_bat32_rt


print('\n\n')
print('#'*60)
print('#'*15, "\t Confidence Intervall: ", '#'*15, sep='')
print('#'*60)

conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time: \t\t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}%:  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)




############################################################
###############	 Confidence Intervall: ###############
############################################################

 Test-Error : 		 Mean = 20.06204, 
	 Confidence interval 0.98% = [19.99926, 20.12482]

 Running-Time: 		 Mean = 7.638, 
	 Confidence interval 0.98%:  [5.818, 9.458]




In [61]:
# parm_bat_128:

# parm_bat128_te = [20.19735, 20.17375, 19.98697, 20.11189, 20.06467]
# parm_bat128_rt = [10.507, 11.879, 6.817, 11.947, 6.362]


parm_test_error   = parm_bat64_te
parm_running_time = parm_bat64_rt

print('\n\n')
print('#'*60)
print('#'*15, "\t Confidence Intervall: ", '#'*15, sep='')
print('#'*60)

conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time: \t\t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}%:  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)




############################################################
###############	 Confidence Intervall: ###############
############################################################

 Test-Error : 		 Mean = 20.12628, 
	 Confidence interval 0.98% = [19.88421, 20.36835]

 Running-Time: 		 Mean = 10.192, 
	 Confidence interval 0.98%:  [6.019, 14.365]




In [62]:
# parm_bat_128:

parm_test_error   = parm_bat128_te
parm_running_time = parm_bat128_rt
print('\n\n')
print('#'*60)
print('#'*15, "\t Confidence Intervall: ", '#'*15, sep='')
print('#'*60)

conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time: \t\t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}%:  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)




############################################################
###############	 Confidence Intervall: ###############
############################################################

 Test-Error : 		 Mean = 20.10693, 
	 Confidence interval 0.98% = [19.96464, 20.24922]

 Running-Time: 		 Mean = 9.502, 
	 Confidence interval 0.98%:  [4.936, 14.069]




In [ ]:
parm_bat32_te = [20.0913, 20.0092, 20.0785, 20.0367, 20.0945]
parm_bat32_rt = [7.44, 7.34, 6.07, 8.69, 8.65]

parm_bat64_te = [20.2225, 20.2962, 20.1555, 19.9577, 19.9995]
parm_bat64_rt = [10.26, 14.27, 8.27, 8.08, 10.08]

parm_bat128_te = [20.19735, 20.17375, 19.98697, 20.11189, 20.06467]
parm_bat128_rt = [10.507, 11.879, 6.817, 11.947, 6.362]


# 32:
 Test-Error : 		 Mean = 20.06204, 
	 Confidence interval 0.98% = [19.99926, 20.12482]
# 64:
 Test-Error : 		 Mean = 20.12628, 
	 Confidence interval 0.98% = [19.88421, 20.36835]
# 128:
 Test-Error : 		 Mean = 20.10693, 
	 Confidence interval 0.98% = [19.96464, 20.24922]


# 32:
 Running-Time: 		 Mean = 7.638, 
	 Confidence interval 0.98%:  [5.818, 9.458]
# 64:
 Running-Time: 		 Mean = 10.192, 
	 Confidence interval 0.98%:  [6.019, 14.365]
# 128:
 Running-Time: 		 Mean = 9.502, 
	 Confidence interval 0.98%:  [4.936, 14.069]


## def_dataset(norm_subject, norm_random):
 * dataset_name: 	   norm_labels.csv
 * dataset_size:       train: 1000, 	 test: 200
 * dataset-splits: 	   norm_subject vs. norm_random      <============
 * batch_Size: 	       128
 * learning_rate: 	   1e-4

	 dataset_name: 	 norm_labels.csv
	 def_dataset_size: train: 1000, 	 test: 200
	 batch_Size: 	 128
	 def_dataset: 	 norm_subject
	 learning_rate: 	 0.0001
	 epochs: 	 500
	 patience: 	 3

# dataset-splits: 	 norm_subject
 
* ** try 1 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 9.30 min	 | improvements: 2 Epochen	 | best_test_error: 20.1205 % 

* ** try 2 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 9.25 min	 | improvements: 2 Epochen	 | best_test_error: 20.0771 % 

* ** try 3 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 9.22 min	 | improvements: 2 Epochen	 | best_test_error: 20.0507 %

* ** try 4 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 9.04 min	 | improvements: 2 Epochen	 | best_test_error: 20.0485 % 

* ** try 5 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 9.21 min	 | improvements: 2 Epochen	 | best_test_error: 20.0101 % 

* ** try 6 **:
last_layer: Sigmoid	 epochs: 5 Epochen	| running_time: 11.28 min	 | improvements: 3 Epochen	 | best_test_error: 19.9546 %

parm_norm_sub_te = [20.1205, 20.0771, 20.0507, 20.0485, 20.0101, 19.9546]
parm_norm_sub_rt = [9.30, 9.25, 9.22, 9.04, 9.21, 11.28]


########################################################################
# dataset-splits: 	 norm_random

* ** try 1 **:
last_layer: Sigmoid	 epochs: 3 Epochen	| running_time: 7.24 min	 | improvements: 1 Epochen	 | best_test_error: 18.8797 %

* ** try 2 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 9.14 min	 | improvements: 2 Epochen	 | best_test_error: 18.8308 %

* ** try 3 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 9.24 min	 | improvements: 2 Epochen	 | best_test_error: 18.8890 %

* ** try 4 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 8.98 min	 | improvements: 2 Epochen	 | best_test_error: 18.8544 %

* ** try 5 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 9.72 min	 | improvements: 2 Epochen	 | best_test_error: 18.9156 %

* ** try 6 **:
last_layer: Sigmoid	 epochs: 4 Epochen	| running_time: 9.17 min	 | improvements: 2 Epochen	 | best_test_error: 18.8534 %


parm_norm_random_te = [18.8797, 18.8308, 18.8890, 18.8544, 18.9156, 18.8534]
parm_norm_random_rt = [7.24, 9.14, 9.24, 8.98, 9.72, 9.17]

In [70]:

parm_norm_sub_te = [20.1205, 20.0771, 20.0507, 20.0485, 20.0101, 19.9546]
parm_norm_sub_rt = [9.30, 9.25, 9.22, 9.04, 9.21, 11.28]

parm_norm_random_te = [18.8797, 18.8308, 18.8890, 18.8544, 18.9156, 18.8534]
parm_norm_random_rt = [7.24, 9.14, 9.24, 8.98, 9.72, 9.17]

## dataset_size:((10000, 2000) vs. (1000, 200)):
 * dataset_name: 	   norm_labels.csv
 * dataset_size:       (10000, 2000) vs. (1000, 200)    <============  
 * dataset-splits: 	   norm_subject
 * batch_Size: 	       32
 * learning_rate: 	   1e-4   

# Dataset_size : 10000 & 2000 vs 1000 & 200


In [26]:
# Dataset_size: 10000 & 2000
dataset_size1 = [19.69159, 19.67359, 19.69785, 19.69303, 19.65619]           # 10000: train & 2000: test 
running_time1  = [78.84, 76.00, 59.63, 76.33, 74.14]


# Dataset_size: 1000 & 200
dataset_size2 = [20.08953, 20.04193, 20.06257, 20.10499, 20.04419]           # 1000:  train & 200:  test
running_time2 = [7.06, 7.91, 7.48, 5.75, 7.63]


test_error1 = dataset_size1
test_error2 = dataset_size2

run_time1 = running_time1
run_time2 = running_time2

###############	 Confidence Intervall: ###############

parm_test_error   = test_error1
parm_running_time = run_time1


thema = "Dataset_size = 10000 & 2000"
print(f'\n\n  Thema: \t {thema} \n')

print('#'*15, "\t Confidence Intervall: \t", '#'*20, sep='')


conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error1 : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time1 : \t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}%:  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)



###############	 Confidence Intervall: ###############

parm_test_error   = test_error2
parm_running_time = run_time2


thema = "Dataset_size = 1000 & 200"
print(f'\n\n  Thema: \t {thema} \n')

print('#'*15, "\t Confidence Intervall: \t", '#'*20, sep='')


conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error2 : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time2 : \t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}%:  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)




  Thema: 	 Dataset_size = 10000 & 2000 

###############	 Confidence Intervall: 	####################

 Test-Error1 : 		 Mean = 19.68245, 
	 Confidence interval 0.98% = [19.65342, 19.71148]

 Running-Time1 : 	 Mean = 72.988, 
	 Confidence interval 0.98%:  [60.165, 85.811]




  Thema: 	 Dataset_size = 1000 & 200 

###############	 Confidence Intervall: 	####################

 Test-Error2 : 		 Mean = 20.06864, 
	 Confidence interval 0.98% = [20.02195, 20.11533]

 Running-Time2 : 	 Mean = 7.166, 
	 Confidence interval 0.98%:  [5.743, 8.589]




# trainable model layers: layer 4 & FC vs. only FC

In [18]:
# FC + lay 4:
test_error1  =  [19.95091, 20.2972, 20.07323, 20.04155, 20.19138]
run_time1    =  [7.626, 10.104, 7.248, 7.389, 7.081]

# FC only:
test_error2  = [20.08953, 20.04193, 20.06257, 20.10499, 20.04419]
run_time2    = [7.057, 7.908, 7.478, 5.753, 7.628]


###############	 Confidence Intervall: ###############

parm_test_error   = test_error1
parm_running_time = run_time1


thema = "trainable model-layers: layer 4 & fc"
print(f'\n\n  Thema: \t {thema} \n')

print('#'*15, "\t Confidence Intervall: \t", '#'*20, sep='')


conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error1 : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time1 : \t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}% =  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)



###############	 Confidence Intervall: ###############

parm_test_error   = test_error2
parm_running_time = run_time2


thema = "trainable model-layers: only fc"
print(f'\n\n  Thema: \t {thema} \n')

print('#'*15, "\t Confidence Intervall: \t", '#'*20, sep='')


conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error2 : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time2 : \t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}% =  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)


################### trainable model-layers: layer 4 & fc 
# Test-Error1 : 		 
Mean = 20.11085, 
Confidence interval 0.98% = [19.88447, 20.33724]

# Running-Time1 : 	 
Mean = 7.890, 
Confidence interval 0.98% =  [5.788, 9.991]


################## trainable model-layers: only fc 
# Test-Error2 : 		 
Mean = 20.06864 
Confidence interval 0.98% = [20.02195, 20.11533]

# Running-Time2 : 	 
Mean = 7.165 
Confidence interval 0.98% =  [5.745, 8.584]



  Thema: 	 trainable model-layers: layer 4 & fc 

###############	 Confidence Intervall: 	####################

 Test-Error1 : 		 Mean = 20.11085, 
	 Confidence interval 0.98% = [19.88447, 20.33724]

 Running-Time1 : 	 Mean = 7.890, 
	 Confidence interval 0.98%:  [5.788, 9.991]




  Thema: 	 trainable model-layers: only fc 

###############	 Confidence Intervall: 	####################

 Test-Error2 : 		 Mean = 20.06864, 
	 Confidence interval 0.98% = [20.02195, 20.11533]

 Running-Time2 : 	 Mean = 7.165, 
	 Confidence interval 0.98%:  [5.745, 8.584]




In [ ]:
 dataset_name: 	 norm_labels.csv

 def_dataset_size: train: 1000, 	 test: 200

 batch_Size: 	 32

 def_dataset: 	 norm_subject

 learning_rate: 	 0.0001

In [ ]:
# loss 1:
test_error1 = [20.0098, 	20.2339, 	20.0127, 	20.2048, 	20.1970]
run_time1 = [8.15, 		8.67, 		9.12, 		15.50, 		10.61]

# loss 2 (loss_sensetive)
test_error2 = [20.1656, 	20.2252, 	20.1940, 	20.1018, 	20.1746]
run_time2 = [14.84, 		9.96, 		13.57, 		11.91, 		8.09]



###############	 Confidence Intervall: ###############

parm_test_error   = test_error1
parm_running_time = run_time1


thema = "loss_func = loss1"
print(f'\n\n  Thema: \t {thema} \n')

print('#'*15, "\t Confidence Intervall: \t", '#'*20, sep='')


conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error1 : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time1 : \t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}%:  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)



###############	 Confidence Intervall: ###############

parm_test_error   = test_error2
parm_running_time = run_time2


thema = "loss_func = loss2(loss_sensetive)"
print(f'\n\n  Thema: \t {thema} \n')

print('#'*15, "\t Confidence Intervall: \t", '#'*20, sep='')


conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error2 : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time2 : \t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}%:  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)


############### loss_func = loss1 
# Test-Error1 : 		 
Mean = 20.13164, 
Confidence interval 0.98 % = [19.94604, 20.31724]

# Running-Time1 : 	 
Mean = 10.410
Confidence interval 0.98 % =  [5.401, 15.419]




############### loss_func = loss2(loss_sensetive) 
# Test-Error2 : 		 
Mean = 20.17224 
Confidence interval 0.98% = [20.09596, 20.24852]

# Running-Time2 : 	 
Mean = 11.674
Confidence interval 0.98%:  [7.127, 16.221]

In [90]:
"""     
     dataset_name: 	 norm_labels.csv
	 def_dataset_size: train: 1000, 	 test: 200
	 batch_Size: 	 128
	 def_dataset: 	 norm_subject
	 learning_rate: 	 XXXXXXXXXXXXXXXXXXX
	 epochs: 	 500
	 patience: 	 3

"""

# 1e-3:

best_test_error_3 = [20.08309, 20.07633, 20.14909, 20.1672, 20.12841]
running_time_3    = [6.39,     7.94,     6.29,     6.99,    7.01]

########################################################################
# 1e-4:

best_test_error_4 = [20.03305, 20.00925, 20.0298, 20.04046, 19.99575] 
running_time_4    = [9.125,    9.68,     6.48,    8.37,     6.49] 
########################################################################
# 1e-5:

best_test_error_5 = [20.08512, 20.10841, 20.11687, 20.10085, 20.11486] 
running_time_5    = [8.31,     12.15,    12.055, 6.50,          8.39]

########################################################################
# 1e-6:

best_test_error_6 = [20.32283, 20.0783, 20.05378, 20.33607, 20.36392]
running_time_6    = [6.50,     17.73,   19.66,    8.37,     6.50]


######################################################
###############	 Confidence Intervall: ###############
######################################################

parm_test_error   = best_test_error_3

parm_running_time = running_time_3


thema = "lr = 1e-3"
print(f'\n\n  Thema: \t {thema} \n')

print('#'*15, "\t Confidence Intervall: ", '#'*15, sep='')


conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error1 : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time1 : \t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}%:  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)


######################################################
###############	 Confidence Intervall: ###############
######################################################

parm_test_error   = best_test_error_4
parm_running_time = running_time_4


thema = "lr = 1e-4"
print(f'\n\n  Thema: \t {thema} \n')

print('#'*15, "\t Confidence Intervall: ", '#'*15, sep='')


conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error1 : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time1 : \t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}%:  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)


######################################################
###############	 Confidence Intervall: ###############
######################################################

parm_test_error   = best_test_error_5
parm_running_time = running_time_5


thema = "lr = 1e-5"
print(f'\n\n  Thema: \t {thema} \n')

print('#'*15, "\t Confidence Intervall: ", '#'*15, sep='')


conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error1 : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time1 : \t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}%:  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)


######################################################
###############	 Confidence Intervall: ###############
######################################################

parm_test_error   = best_test_error_6
parm_running_time = running_time_6

thema = "lr = 1e-6"
print(f'\n\n  Thema: \t {thema} \n')

print('#'*15, "\t Confidence Intervall: ", '#'*15, sep='')


conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error1 : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time1 : \t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}%:  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)

############### lr = 1e-3 
# Test-Error1 : 		 
Mean = 20.12082
Confidence interval 0.98% = [20.05374, 20.18791]

# Running-Time1 : 	 
Mean = 6.924, 
Confidence interval 0.98% =  [5.822, 8.026]


############### lr = 1e-4 
# Test-Error1 : 		 
Mean = 20.02166
Confidence interval 0.98% = [19.99060, 20.05273]

# Running-Time1 : 	 
Mean = 8.029 
Confidence interval 0.98% =  [5.542, 10.516]


############### lr = 1e-5 
# Test-Error1 : 		 
Mean = 20.10522
Confidence interval 0.98% = [20.08367, 20.12678]

# Running-Time1 : 	 
Mean = 9.481 
Confidence interval 0.98% =  [5.275, 13.687]


############### lr = 1e-6 
# Test-Error1 : 		 
Mean = 20.23098
Confidence interval 0.98% = [19.97704, 20.48492]

# Running-Time1 : 	 
Mean = 11.752, 
Confidence interval 0.98% =  [0.994, 22.510]




  Thema: 	 lr = 1e-3 

###############	 Confidence Intervall: ###############

 Test-Error1 : 		 Mean = 20.12082, 
	 Confidence interval 0.98% = [20.05374, 20.18791]

 Running-Time1 : 	 Mean = 6.924, 
	 Confidence interval 0.98%:  [5.822, 8.026]




  Thema: 	 lr = 1e-4 

###############	 Confidence Intervall: ###############

 Test-Error1 : 		 Mean = 20.02166, 
	 Confidence interval 0.98% = [19.99060, 20.05273]

 Running-Time1 : 	 Mean = 8.029, 
	 Confidence interval 0.98%:  [5.542, 10.516]




  Thema: 	 lr = 1e-5 

###############	 Confidence Intervall: ###############

 Test-Error1 : 		 Mean = 20.10522, 
	 Confidence interval 0.98% = [20.08367, 20.12678]

 Running-Time1 : 	 Mean = 9.481, 
	 Confidence interval 0.98%:  [5.275, 13.687]




  Thema: 	 lr = 1e-6 

###############	 Confidence Intervall: ###############

 Test-Error1 : 		 Mean = 20.23098, 
	 Confidence interval 0.98% = [19.97704, 20.48492]

 Running-Time1 : 	 Mean = 11.752, 
	 Confidence interval 0.98%:  [0.994, 22.510

In [92]:
# Splits-type: norm_random vs. norm_subject:


parm_norm_sub_te = [20.1205, 20.0771, 20.0507, 20.0485, 20.0101, 19.9546]
parm_norm_sub_rt = [9.30, 9.25, 9.22, 9.04, 9.21, 11.28]

parm_norm_random_te = [18.8797, 18.8308, 18.8890, 18.8544, 18.9156, 18.8534]
parm_norm_random_rt = [7.24, 9.14, 9.24, 8.98, 9.72, 9.17]


###############	 Confidence Intervall: ###############

parm_test_error   = parm_norm_sub_te
parm_running_time = parm_norm_sub_rt


thema = "Splits-type: subjectindipended"
print(f'\n\n  Thema: \t {thema} \n')

print('#'*15, "\t Confidence Intervall: \t", '#'*20, sep='')


conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error1 : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time1 : \t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}%:  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)



###############	 Confidence Intervall: ###############

parm_test_error   = parm_norm_random_te
parm_running_time = parm_norm_random_rt


thema = "Splits-type: norm_random"
print(f'\n\n  Thema: \t {thema} \n')

print('#'*15, "\t Confidence Intervall: \t", '#'*20, sep='')


conf = 0.98

test_error_confidence = confidence_interval(parm_test_error, conf)
run_time_confidence   = confidence_interval(parm_running_time, conf)

print(
    f"\n Test-Error2 : \t\t Mean = {test_error_confidence[0]:.5f}, "
    f"\n\t Confidence interval {conf}% = [{test_error_confidence[1]:.5f}, {test_error_confidence[2]:.5f}]"
)

print(
    f"\n Running-Time2 : \t Mean = {run_time_confidence[0]:.3f}, "
    f"\n\t Confidence interval {conf}%:  [{run_time_confidence[1]:.3f}, {run_time_confidence[2]:.3f}]\n\n"
)


############### Splits-type: subjectindipended 
# Test-Error1 : 		 
Mean = 20.04358 
Confidence interval 0.98% = [19.96550, 20.12167]

# Running-Time1 : 	 
Mean = 9.550 
Confidence interval 0.98% =  [8.380, 10.720]



############### Splits-type: norm_random 
# Test-Error2 : 		 
Mean = 18.87048
Confidence interval 0.98% = [18.82887, 18.91210]

# Running-Time2 : 	 
Mean = 8.915 
Confidence interval 0.98% =  [7.737, 10.093] 



  Thema: 	 Splits-type: subjectindipended 

###############	 Confidence Intervall: 	####################

 Test-Error1 : 		 Mean = 20.04358, 
	 Confidence interval 0.98% = [19.96550, 20.12167]

 Running-Time1 : 	 Mean = 9.550, 
	 Confidence interval 0.98%:  [8.380, 10.720]




  Thema: 	 Splits-type: norm_random 

###############	 Confidence Intervall: 	####################

 Test-Error2 : 		 Mean = 18.87048, 
	 Confidence interval 0.98% = [18.82887, 18.91210]

 Running-Time2 : 	 Mean = 8.915, 
	 Confidence interval 0.98%:  [7.737, 10.093]


